/**
 * #4610 / CERT-2456 — A REFUSED LADDER STILL SHOWS THE READER ITS FIELD.
 *
 * ═══ THE DEFECT THIS FILE EXISTS FOR ═══
 *
 * "Netflix App Downloads in September" served three rungs whose prices cannot
 * all be true of one cumulative ladder. #4610 stopped the impossible rung being
 * a card's leader; CERT-2451 then found that the fix hid the whole card's field,
 * because the serializer filtered the bad rungs out and handed the classifier a
 * lone survivor, which came back as a one-point `threshold_heatmap` that the
 * frontend cannot draw.
 *
 * CERT-2456 found the SAME reader-facing failure surviving that repair, one
 * fallback further on. With the drop refused, all three rungs travel — but the
 * card is three rows and the cascade's field branch starts at four, so it fell
 * to `binary_probability`, whose hero prints the leader ALONE. Three fixes in,
 * the reader still met one number where three rungs had been.
 *
 * ⚠️ WHY THE BACKEND TESTS COULD NOT CATCH THAT, AND THIS FILE CAN.
 * `test_incoherent_ladder_rung_4610.py` stops at the payload boundary. Every
 * assertion it makes about this specimen was TRUE at the blocked commit: three
 * rows in `top_outcomes`, three in `distribution_outcomes`, no threshold
 * points. The field was in the payload and absent from the screen. The only
 * test that can tell those apart renders the component.
 *
 * ═══ THE FIXTURE IS NOT INVENTED ═══
 *
 * `refusedLadderField4610.json` is the REAL output of `_score_futures` over the
 * specimen — generated by the backend, not typed here — and
 * `TestTheFrontendFixtureIsStillWhatWeServe` in the backend suite fails if the
 * serializer ever stops producing it. Same seam, same reason, as
 * `test_playoff_degraded_contract.py`: nothing imports across Python and
 * TypeScript, so a hand-written payload would keep this file green long after
 * the producer changed shape.
 *
 * ═══ EVERY ABSENCE HERE IS PAIRED WITH A PRESENCE ═══
 *
 * A card that rendered nothing satisfies `not.toContain("heatmap")` perfectly,
 * and an empty render reads exactly like a clean pass. So the render PATH is
 * pinned by its `data-card-format` marker in both directions, and the
 * flag-stripped control below asserts the defect reproduces rather than merely
 * asserting the fix passes.
 */

import { renderToStaticMarkup } from "react-dom/server";
import React from "react";
import type { FeedFuturesData, FeedItem } from "@/lib/types";
import type { DiscoverGroupedItem } from "@/components/discover/types";

jest.mock("next/navigation", () => ({
  __esModule: true,
  useRouter: () => ({ push: jest.fn(), replace: jest.fn(), prefetch: jest.fn() }),
}));
jest.mock("next/link", () => ({
  __esModule: true,
  default: ({ href, children }: { href: string; children: React.ReactNode }) => (
    <a href={href}>{children}</a>
  ),
}));
jest.mock("next/image", () => ({
  __esModule: true,
  default: ({ alt }: { alt: string }) => <img alt={alt} />,
}));
jest.mock("@/components/Analytics", () => ({
  __esModule: true,
  useAnalyticsContext: () => ({ track: () => {} }),
}));

import DiscoverCard from "../../components/DiscoverCard";
import SERVED_CARD from "../fixtures/refusedLadderField4610.json";

/** The three rungs the reader is owed. */
const RUNGS = ["Above 30", "Above 20", "Above 10"];

function render(data: unknown): string {
  const item = {
    type: "futures",
    score: 90,
    reason: "",
    headline: "",
    data: data as unknown as FeedFuturesData,
  } as unknown as FeedItem;
  return renderToStaticMarkup(
    <DiscoverCard groupedItem={{ type: "item", item } as unknown as DiscoverGroupedItem} />
  );
}

/** A deep copy, so one test's edit cannot leak into the next. */
function servedCard(): Record<string, unknown> {
  return JSON.parse(JSON.stringify(SERVED_CARD));
}

describe("#4610 — a refused three-rung ladder renders its field", () => {
  it("test_refused_three_rung_ladder_renders_all_outcomes", () => {
    const markup = render(servedCard());

    // ── the field: all three rungs on the screen, not just the leader ──
    for (const rung of RUNGS) {
      expect(markup).toContain(rung);
    }

    // ── and no ladder treatment, which is what was refused ──
    expect(markup).not.toContain('data-card-format="heatmap"');

    // The paired positive: absence of the heatmap only means something once we
    // know WHICH root rendered. Without this, a card that fell through to the
    // plain leader hero — the exact CERT-2456 defect — passes both checks above
    // for "Above 30" alone.
    expect(markup).toContain('data-card-format="leaderboard"');
  });

  it("prints the rungs as ranked rows, not as one hero number", () => {
    const markup = render(servedCard());
    // The leaderboard marks each named row with `aria-label="Rank N"`. Three
    // rungs, three ranks — this is the assertion that fails if the card renders
    // the leader as a hero and the other two as incidental text somewhere.
    const ranks = [...markup.matchAll(/aria-label="Rank (\d+)"/g)].map((m) => Number(m[1]));
    expect(ranks).toEqual([1, 2, 3]);

    // Leader first (#1526): the rows are sorted before slicing.
    const order = RUNGS.map((label) => ({ label, at: markup.indexOf(label) }))
      .sort((a, b) => a.at - b.at)
      .map((x) => x.label);
    expect(order).toEqual(["Above 30", "Above 20", "Above 10"]);
  });

  it("does not tell the reader that rungs are missing, because none are", () => {
    // The drop was REFUSED, so every rung is on the card. A "+N more" row here
    // would be the card claiming a field it is already showing in full.
    const markup = render(servedCard());
    expect(markup).not.toContain("Field and remaining outcomes");
  });

  // ── the control that makes the flag load-bearing ────────────────────────────
  it("RED-FIRST: without the served refusal flag, the field disappears", () => {
    // This is the blocked commit's behaviour, reproduced from the same payload
    // with one key removed. It is what makes the assertions above a guard
    // rather than a description: if the leaf gate stopped consulting the flag
    // and simply drew every three-row distribution, this test would go green
    // for the wrong reason and nothing else in the file would notice.
    const stripped = servedCard();
    delete (stripped.discover_card as Record<string, unknown>).ladder_treatment_refused;

    const markup = render(stripped);
    expect(markup).not.toContain('data-card-format="leaderboard"');
    expect(markup).not.toContain("Above 20");
    expect(markup).not.toContain("Above 10");
    // The leader survives — which is precisely why the defect read as a working
    // card to everything that looked at the payload.
    expect(markup).toContain("Above 30");
  });

  it("CONTROL: an unrefused three-row distribution still keeps the old gate", () => {
    // The widening is scoped to the refusal, so no card that renders correctly
    // today changes shape. Same three rows, flag false: the `>= 4` bar applies
    // exactly as it did before this ship.
    const unrefused = servedCard();
    (unrefused.discover_card as Record<string, unknown>).ladder_treatment_refused = false;

    const markup = render(unrefused);
    expect(markup).not.toContain('data-card-format="leaderboard"');
  });
});
