import XCTest
@testable import Bain_Luck

@MainActor final class WatchAwardsTests: XCTestCase {
    // Generated by the retained exact-base awards producer using synthetic database rows.
    // NOT production data. Keep in sync with fixtures/oscars-producer.json in the source packet.
    nonisolated private static let producerJSON = #"""
{
  "event": {
    "key": "event:awards:oscars-2027",
    "domain": "awards",
    "name": "The Oscars 2027",
    "status": "upcoming",
    "start_date": null,
    "end_date": null,
    "venue": null,
    "location": null,
    "is_major": true
  },
  "primary": {
    "kind": "co_equal_list",
    "label": "Best Picture",
    "competitors": [
      {
        "name": "Anora",
        "probability": 0.6,
        "won": false
      },
      {
        "name": "The Brutalist",
        "probability": 0.4,
        "won": false
      }
    ],
    "evolution_market_id": 101,
    "price_observed_at": null
  },
  "sections": [
    {
      "type": "categories",
      "label": "Categories",
      "market_ids": [
        101,
        202
      ]
    },
    {
      "type": "props",
      "label": "Nominations & props",
      "market_ids": [
        303
      ]
    }
  ],
  "children": [
    {
      "market_id": 101,
      "market_name": "Best Picture",
      "source": "kalshi",
      "settled": false,
      "probability": 0.6,
      "outcomes": [
        {
          "name": "Anora",
          "probability": 0.6
        },
        {
          "name": "The Brutalist",
          "probability": 0.4
        }
      ]
    },
    {
      "market_id": 202,
      "market_name": "Best Director",
      "source": "kalshi",
      "settled": true,
      "probability": 0.6,
      "outcomes": [
        {
          "name": "Sean Baker",
          "probability": 0.6
        },
        {
          "name": "Brady Corbet",
          "probability": 0.4
        }
      ]
    },
    {
      "market_id": 303,
      "market_name": "Best Picture",
      "source": "kalshi",
      "settled": false,
      "probability": 0.6,
      "outcomes": [
        {
          "name": "Anora",
          "probability": 0.6
        },
        {
          "name": "Wicked",
          "probability": 0.4
        }
      ],
      "kind": "prop",
      "prop_type": "nominations"
    }
  ],
  "movers": [],
  "cache": {
    "generation": 3,
    "created_at": "2026-10-10T00:00:00+00:00",
    "quality": "full",
    "availability": "live",
    "lifecycle_watermark": null,
    "quality_reasons": []
  }
}
"""#

    private func object() throws -> [String: Any] {
        try XCTUnwrap(JSONSerialization.jsonObject(with: Data(Self.producerJSON.utf8)) as? [String: Any])
    }
    private func decode(_ object: [String: Any], key: String = "event:awards:oscars") throws -> WatchAwardsPage {
        try WatchAwardsDecoder.decode(JSONSerialization.data(withJSONObject: object), ceremony: .oscars, requestedKey: key)
    }

    func testProducerCategoriesOpenExactMarketsWithoutPromotingCeremonyWinners() throws {
        var json = try object()
        let page = try decode(json)
        XCTAssertEqual(page.key, "event:awards:oscars-2027")
        XCTAssertEqual(page.categories.map(\.id), [101, 202])
        XCTAssertEqual(page.categories.map(\.name), ["Best Picture", "Best Director"])
        XCTAssertEqual(page.categories.map(\.resultUnconfirmed), [false, true])
        XCTAssertFalse(page.isSaved)
        XCTAssertFalse(page.hasUnavailableCategories)
        // The producer's marquee winner and probability/clock cannot grade a sibling.
        json["primary"] = ["competitors": [["name": "Invented winner", "won": true, "probability": 1.0]],
                           "price_observed_at": "2026-10-10T23:00:00Z"]
        XCTAssertEqual(try decode(json), page)
    }

    func testCeremonyAndEditionMustMatchAndRoutesCannotEscape() throws {
        let json = try object()
        XCTAssertThrowsError(try decode(json, key: "event:awards:oscars-2026"))
        for key in ["event:awards:emmys", "event:awards:oscars/../../other", "event:awards:oscars-2027?x=1",
                    "https://example.com", "event:awards:oscars-27", "event:awards:oscars-２０２７"] {
            XCTAssertFalse(WatchAwardsCeremony.oscars.accepts(key: key))
        }
        for event in [["domain": "golf", "key": "event:awards:oscars-2027", "name": "Other"],
                      ["domain": "awards", "key": "event:awards:emmys-2027", "name": "Other"]] {
            var bad = json; bad["event"] = event
            XCTAssertThrowsError(try decode(bad))
        }
    }

    func testMalformedAndDuplicateCategoriesCannotAuthorizeDestinations() throws {
        var json = try object()
        var children = try XCTUnwrap(json["children"] as? [[String: Any]])
        children.append(children[0])
        children.append(["market_id": "not an integer", "market_name": "Bad"])
        json["children"] = children
        let page = try decode(json)
        XCTAssertEqual(page.categories.map(\.id), [202])
        XCTAssertTrue(page.hasUnavailableCategories)
        json["sections"] = [["type": "categories", "market_ids": [202, 202, 303, -1, 999]]]
        XCTAssertEqual(try decode(json).categories.map(\.id), [202], "Props and unbound IDs cannot become categories")
    }

    func testMalformedDuplicateStillBlocksItsReadableCategoryIdentity() throws {
        let original = try object()
        let children = try XCTUnwrap(original["children"] as? [[String: Any]])
        let malformedClaims: [[String: Any]] = [
            ["market_id": 101, "market_name": 42],
            ["market_id": 101, "market_name": "Conflicting category", "settled": "unknown"],
            ["market_id": 101, "market_name": "Conflicting category", "kind": 42]
        ]
        for claim in malformedClaims {
            for duplicateFirst in [false, true] {
                var json = original
                json["children"] = duplicateFirst ? [claim] + children : children + [claim]
                let page = try decode(json)
                XCTAssertEqual(page.categories.map(\.id), [202],
                    "Malformed duplicate must not authorize category 101; healthy category 202 survives")
                XCTAssertTrue(page.hasUnavailableCategories)
            }
        }
    }

    func testCacheAvailabilityAndUnknownGradeRemainExplicit() throws {
        var json = try object()
        json["cache"] = ["availability": "stale_ok", "quality": "partial"]
        var children = try XCTUnwrap(json["children"] as? [[String: Any]])
        children[0].removeValue(forKey: "settled")
        json["children"] = children
        let page = try decode(json)
        XCTAssertTrue(page.isSaved)
        XCTAssertTrue(page.hasUnavailableCategories)
        XCTAssertTrue(page.categories[0].resultUnconfirmed)
        for availability in ["unavailable", "unknown"] {
            json["cache"] = ["availability": availability, "quality": "full"]
            XCTAssertThrowsError(try decode(json))
        }
    }

    private actor Transport: WatchAwardsTransport {
        private(set) var keys: [String] = []
        private var replies: [Int: CheckedContinuation<WatchAwardsPage, Error>] = [:]
        func fetch(ceremony: WatchAwardsCeremony, key: String) async throws -> WatchAwardsPage {
            let index = keys.count
            keys.append(key)
            return try await withCheckedThrowingContinuation { replies[index] = $0 }
        }
        func complete(_ index: Int, with response: Result<WatchAwardsPage, Error>) {
            replies.removeValue(forKey: index)?.resume(with: response)
        }
        func count() -> Int { keys.count }
    }
    private func waitForCalls(_ count: Int, _ transport: Transport) async throws {
        for _ in 0..<100 {
            if await transport.count() >= count { return }
            try await Task.sleep(for: .milliseconds(10))
        }
        XCTFail("Expected ceremony request did not start")
        throw WatchAwardsError.invalid
    }

    func testRefreshPinsEditionAndFailureRemovesStaleDestinations() async throws {
        let transport = Transport(), store = WatchAwardsStore(transport: transport)
        let page = try decode(object())
        let first = Task { await store.open(.oscars) }
        try await waitForCalls(1, transport)
        await transport.complete(0, with: .success(page)); await first.value
        XCTAssertEqual(store.category(id: 202)?.name, "Best Director")
        let retry = Task { await store.refresh() }
        try await waitForCalls(2, transport)
        XCTAssertNil(store.category(id: 202), "Old rows cannot be tapped while refreshing")
        let keys = await transport.keys
        XCTAssertEqual(keys, ["event:awards:oscars", "event:awards:oscars-2027"])
        await transport.complete(1, with: .failure(URLError(.notConnectedToInternet))); await retry.value
        XCTAssertNil(store.page)
        XCTAssertTrue(store.errorMessage?.hasPrefix("Offline.") == true)
        XCTAssertEqual(store.ceremony, .oscars, "Retry and return context survive failure")
        let recovery = Task { await store.refresh() }
        try await waitForCalls(3, transport)
        await transport.complete(2, with: .success(page)); await recovery.value
        XCTAssertEqual(store.category(id: 202)?.id, 202)
        XCTAssertNil(store.errorMessage)
        let drift = Task { await store.refresh() }
        try await waitForCalls(4, transport)
        let wrongEdition = WatchAwardsPage(key: "event:awards:oscars-2028", name: "The Oscars 2028",
            categories: page.categories, isSaved: false, hasUnavailableCategories: false)
        await transport.complete(3, with: .success(wrongEdition)); await drift.value
        XCTAssertNil(store.page, "A later refresh cannot silently switch ceremony editions")
        XCTAssertNotNil(store.errorMessage)
    }

    func testDismissAndCeremonySwitchRejectLateReplies() async throws {
        let transport = Transport(), store = WatchAwardsStore(transport: transport)
        let oldPage = try decode(object())
        let old = Task { await store.open(.oscars) }
        try await waitForCalls(1, transport)
        store.browse()
        let newer = Task { await store.open(.emmys) }
        try await waitForCalls(2, transport)
        let newPage = WatchAwardsPage(key: "event:awards:emmys-2027", name: "The Emmys 2027",
            categories: [.init(id: 404, name: "Drama Series", resultUnconfirmed: true)],
            isSaved: false, hasUnavailableCategories: false)
        await transport.complete(1, with: .success(newPage)); await newer.value
        await transport.complete(0, with: .success(oldPage)); await old.value
        XCTAssertEqual(store.page, newPage)
        XCTAssertNil(store.category(id: 101))
        let dismissed = Task { await store.refresh() }
        try await waitForCalls(3, transport)
        store.cancel()
        await transport.complete(2, with: .success(newPage)); await dismissed.value
        XCTAssertNil(store.page)
        XCTAssertFalse(store.isLoading)
    }
}
