"""One Redis pub/sub connection per process for every open SSE stream (#6515).

WHAT WAS WRONG. ``routes/event_stream.py`` called ``get_async_redis_client()``
*inside* the stream generator — once per open connection — and that factory is
deliberately uncached, so every stream built its own connection pool and its
``PubSub`` checked a real socket out of that pool for the life of the stream (up
to ``SSE_MAX_CONNECTION_S``, 900 s). N concurrent streams therefore held N
sockets, and no cap on a single pool can bound that: each stream's own pool sat
at 1 of its cap and never queued, so the refusal arrived from the SERVER as
``ERR max number of clients reached``.

That refusal is not confined to SSE. The plan's 80 connections are shared by
every process of both apps, so the next Redis connect from anywhere in the web
dyno — ``utils/request_cache.py``, the rate limiter, the feed cache — fails
alongside it. ``SSE_MAX_CONNECTIONS`` is 200 per uvicorn worker, which is why
the 503 capacity gate that exists to refuse loudly could never fire first:
exhaustion arrived at ~80 readers fleet-wide, not at 200 per worker.

WHAT THIS IS. Redis pub/sub already multiplexes many channels down ONE
connection. So the process keeps one, and every stream reads from its own
bounded mailbox instead of its own socket. N streams cost one socket; zero
streams cost none.

FOUR PROPERTIES, ALL LOAD-BEARING.

* **Release is SYNCHRONOUS.** A stream gives up its subscription from a
  ``finally`` that may be running under cancellation — where the first
  ``await`` re-raises ``CancelledError`` and nothing after it runs. With a
  per-stream client that only risked an untidy close of a client nobody else
  used; with a shared one it would strand the subscriber forever, so the hub
  would never go idle and a channel would keep being delivered to nobody.
  ``release()`` therefore takes no ``await``: it mutates the bookkeeping (atomic
  under a single-threaded loop) and leaves the Redis ``UNSUBSCRIBE`` to the
  reader's next pass.
* **A slow reader drops frames, it never blocks the hub.** Each subscriber has
  a bounded drop-oldest mailbox. A frame is a snapshot of the current
  probability, not an increment, so the newest is the only one worth keeping —
  and ``live_push.MAX_FRAME_AGE_S`` already discards a frame that queued
  through a stall rather than animating the number backwards.
* **Idle means idle.** When the last stream leaves, the reader unsubscribes,
  closes the pub/sub and its client, and exits. A web dyno with nobody watching
  a live match holds no SSE connection at all, and a connection is never left
  idle long enough for Heroku Redis to reap it out from under us.
* **Failure is ANNOUNCED, never silent.** The heartbeat is generated by the
  route, not by Redis, so a dead shared reader would leave every stream looking
  perfectly healthy and permanently frozen — the worst shape this could fail
  in. When the reader stops, every subscriber is handed ``CLOSED``; the route
  turns that into the ``reconnect`` event the client already treats as a
  rollover, and reconnecting rebuilds the hub.

ONE CONNECTION IS NOT A SINGLE POINT OF FAILURE, AND THAT IS MEASURED. redis-py
retries a dropped pub/sub read on the client's own ``retry`` policy, and its
``on_connect`` callback re-subscribes every channel in ``PubSub.channels`` — the
dict ``subscribe()`` above maintains. So a TLS blip costs a reconnect inside one
``get_message`` call and nobody's stream ends; the ``CLOSED`` path is for the
failure that outlives the retry budget. The socket arm
``test_a_dropped_connection_reconnects_without_ending_anyones_stream`` kills the
connection under live readers and watches them keep receiving.

WHY THE CLIENT IS STILL NOT CACHED. ``get_async_redis_client`` stays uncached
and the hub owns its client outright, because the hub ``aclose()``s it when it
goes idle — the same reason the route could never share one. The per-call pools
built by the other async callers (route handlers, the feed cache) are outside
this fix and outside the #1197 envelope; ``tests/test_sse_shares_one_pubsub_
connection_6515.py`` counts every pool-building site so that residual is a
number rather than an impression.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
from typing import Any, Dict, Optional, Set

logger = logging.getLogger(__name__)

#: How long the shared reader blocks on the socket before looping. It is also
#: the interval at which a released channel's ``UNSUBSCRIBE`` and idle teardown
#: are noticed, so it bounds how long a channel nobody wants keeps arriving.
READ_TIMEOUT_S = 1.0

#: Frames one stream may fall behind before its oldest is dropped.
QUEUE_MAX = 8

#: How many times the hub rebuilds its connection before it gives up and tells
#: every stream to reconnect. Small: the announced path is not a failure, it is
#: a five-second rollover the client already performs routinely.
RECONNECT_ATTEMPTS = 3

#: Backoff between rebuild attempts, multiplied by the attempt number. Short
#: enough that a blip costs a reader one missed tick rather than a visible gap.
RECONNECT_BACKOFF_S = 0.2


class _Closed:
    """The shared connection ended; whoever holds this should reconnect."""

    __slots__ = ()

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return "<live_fanout.CLOSED>"


CLOSED = _Closed()


class Subscription:
    """One stream's view of one channel: a bounded, drop-oldest mailbox."""

    __slots__ = ("channel", "_queue", "_dropped")

    def __init__(self, channel: str) -> None:
        self.channel = channel
        self._queue: asyncio.Queue = asyncio.Queue(maxsize=QUEUE_MAX)
        self._dropped = 0

    @property
    def dropped(self) -> int:
        """Frames discarded because this stream fell behind."""
        return self._dropped

    def offer(self, payload: Any) -> None:
        """Deliver, dropping this mailbox's oldest frame if it is full.

        Never blocks and never raises: the hub's single reader calls this once
        per subscriber per frame, so one wedged client must not be able to hold
        up delivery to every other reader on the dyno.
        """
        while True:
            try:
                self._queue.put_nowait(payload)
                return
            except asyncio.QueueFull:
                try:
                    self._queue.get_nowait()
                    self._dropped += 1
                except asyncio.QueueEmpty:  # pragma: no cover - single-threaded
                    return

    async def next(self, timeout: float) -> Any:
        """The next frame, ``CLOSED``, or ``None`` when nothing arrived in time.

        The bounded wait is what keeps the route's heartbeat on its own clock
        through a silent market, exactly as the per-stream
        ``pubsub.get_message(timeout=...)`` did before the hub existed.
        """
        try:
            return await asyncio.wait_for(self._queue.get(), timeout)
        except asyncio.TimeoutError:
            return None


class LiveFanout:
    """Process-wide pub/sub fanout: one Redis connection, N subscribers."""

    def __init__(self) -> None:
        # Guards the compound operations that span an ``await`` on the Redis
        # side (connect, SUBSCRIBE, UNSUBSCRIBE, teardown). Plain dict edits do
        # not need it — the loop is single-threaded — which is what lets
        # ``release()`` stay synchronous.
        self._lock = asyncio.Lock()
        self._subscribers: Dict[str, Set[Subscription]] = {}
        self._pending_unsubscribe: Set[str] = set()
        self._client = None
        self._pubsub = None
        self._reader: Optional[asyncio.Task] = None

    # -- what a guard test reads -------------------------------------------

    @property
    def redis_connections(self) -> int:
        """Sockets this process holds for SSE: one while anyone streams."""
        return 1 if self._pubsub is not None else 0

    @property
    def channels(self) -> frozenset:
        return frozenset(self._subscribers)

    @property
    def subscriber_count(self) -> int:
        return sum(len(subs) for subs in self._subscribers.values())

    # -- the stream's side --------------------------------------------------

    async def subscribe(self, channel: str) -> Subscription:
        """Join ``channel``, connecting the shared pub/sub if it is the first."""
        sub = Subscription(channel)
        async with self._lock:
            # A channel released moments ago may still be subscribed at Redis
            # and merely pending. Claiming it back is cheaper — and cannot
            # cross on the wire with its own UNSUBSCRIBE — because both the
            # cancel and any send happen under this lock.
            self._pending_unsubscribe.discard(channel)
            already = channel in self._subscribers
            self._subscribers.setdefault(channel, set()).add(sub)
            try:
                await self._connect_locked()
                if not already:
                    await self._pubsub.subscribe(channel)
            except BaseException:
                # Nothing partially joined: a caller that saw an exception must
                # not leave a subscriber behind holding the hub open.
                self._forget(sub)
                raise
            self._start_reader_locked()
        return sub

    def release(self, sub: Subscription) -> None:
        """Give up a subscription. SYNCHRONOUS on purpose (module docstring)."""
        if self._forget(sub):
            self._pending_unsubscribe.add(sub.channel)

    # -- the Redis side -----------------------------------------------------

    async def _connect_locked(self) -> None:
        if self._pubsub is not None:
            return
        from app.tasks.redis_state import get_async_redis_client

        self._client = get_async_redis_client()
        self._pubsub = self._client.pubsub()

    def _start_reader_locked(self) -> None:
        # Started only after the first SUBSCRIBE: ``PubSub.parse_response``
        # raises if it is called before the pub/sub has a connection.
        if self._reader is None or self._reader.done():
            self._reader = asyncio.create_task(
                self._read_loop(self._pubsub), name="live-fanout-reader"
            )

    async def _read_loop(self, pubsub) -> None:
        # Consecutive read failures with no successful read between them. A
        # rebuild that "succeeds" and then fails its very next read is not
        # recovery — without this counter a permanently broken connection would
        # be rebuilt forever, hammering Redis and leaving every reader frozen
        # behind a hub that looks busy.
        failures = 0
        try:
            while True:
                # Hand the loop back once per pass, unconditionally. A read that
                # returns without ever awaiting — a broken transport, a stubbed
                # client — would otherwise spin this task and starve `/api/feed`
                # on the same loop, which is the one failure this file exists to
                # prevent. It costs one scheduler tick per second in production.
                await asyncio.sleep(0)
                try:
                    message = await pubsub.get_message(
                        ignore_subscribe_messages=True, timeout=READ_TIMEOUT_S
                    )
                    failures = 0
                except asyncio.CancelledError:
                    raise
                except Exception:
                    failures += 1
                    if failures > RECONNECT_ATTEMPTS:
                        logger.warning(
                            "live_fanout: the shared pub/sub failed %d reads in "
                            "a row; telling every stream to reconnect",
                            failures, exc_info=True,
                        )
                        await self._fail()
                        return
                    await asyncio.sleep(RECONNECT_BACKOFF_S * failures)
                    replacement = await self._rebuild(pubsub)
                    if replacement is None:
                        if not self._subscribers:
                            return  # idle while we were away; nobody to tell
                        continue  # build failed; the counter decides when to stop
                    pubsub = replacement
                    continue
                if message is not None and message.get("type") == "message":
                    self._dispatch(message)
                if self._pending_unsubscribe or not self._subscribers:
                    if await self._housekeep():
                        return
        except asyncio.CancelledError:
            raise
        except Exception:
            # A stream whose frames stop arriving looks identical to a quiet
            # market — the route's heartbeat keeps ticking either way — so the
            # one thing this must not do is end quietly.
            logger.warning(
                "live_fanout: the shared pub/sub reader stopped", exc_info=True
            )
            await self._fail()

    async def _rebuild(self, old):
        """Re-establish the shared connection after a read failed.

        THE OBVIOUS OBJECTION TO SHARING, ANSWERED HERE. A per-stream connection
        died alone and took one reader with it; one connection that died would
        take every reader on the dyno at once — and on Heroku Redis a
        reaped-then-reused connection is a KNOWN recurring event, not a
        hypothetical (it is #1197's whole subject). Measured against a real
        socket, redis-py does NOT paper over this for a pub/sub read: the
        `ConnectionError` comes out of `get_message` and the retry policy above
        it does not put the subscriptions back. So the hub rebuilds and
        re-subscribes every live channel itself, and nobody's stream ends.

        Frames published during the gap are lost, which is the transport's
        stated bargain (`live_push`: pub/sub stores nothing) and self-heals on
        the refresher's next stamp. Giving up is the ANNOUNCED path — `_fail`,
        then every stream reconnects — never a silent freeze.

        ONE ATTEMPT. How many are worth making is the reader loop's question,
        and it counts CONSECUTIVE FAILED READS rather than failed builds — a
        rebuild that connects and then fails its next read has recovered
        nothing, and counting builds would let that loop forever.
        """
        async with self._lock:
            if self._pubsub is old:
                # Still the live handle, and it is the broken one.
                await self._release_connection_locked()
            channels = set(self._subscribers)
            if not channels:
                await self._release_connection_locked()
                self._reader = None
                return None
            try:
                # Builds only if nothing is connected — a subscriber that
                # arrived during the gap may already have built one, and then
                # it holds only ITS channel. Every live channel is
                # (re-)subscribed either way; SUBSCRIBE on a channel Redis is
                # already serving is a confirmation, not a second delivery.
                await self._connect_locked()
                for channel in channels:
                    await self._pubsub.subscribe(channel)
                logger.warning(
                    "live_fanout: shared pub/sub rebuilt (%d channels)",
                    len(channels),
                )
                return self._pubsub
            except Exception:
                logger.warning(
                    "live_fanout: shared pub/sub rebuild failed", exc_info=True
                )
                await self._release_connection_locked()
                return None

    def _dispatch(self, message: dict) -> None:
        channel = _as_text(message.get("channel"))
        subscribers = self._subscribers.get(channel)
        if not subscribers:
            return
        payload = message.get("data")
        for sub in tuple(subscribers):
            sub.offer(payload)

    async def _housekeep(self) -> bool:
        """Send the deferred UNSUBSCRIBEs; report whether the hub went idle."""
        async with self._lock:
            # A channel re-joined since it was released is NOT unsubscribed:
            # ``_subscribers`` is the live answer, the pending set only a hint.
            pending = self._pending_unsubscribe - set(self._subscribers)
            self._pending_unsubscribe.clear()
            for channel in pending:
                try:
                    await self._pubsub.unsubscribe(channel)
                except Exception:
                    logger.debug(
                        "live_fanout: UNSUBSCRIBE %s failed", channel, exc_info=True
                    )
            if self._subscribers:
                return False
            await self._release_connection_locked()
            self._reader = None
            return True

    async def _fail(self) -> None:
        async with self._lock:
            orphans = [sub for subs in self._subscribers.values() for sub in subs]
            self._subscribers.clear()
            await self._release_connection_locked()
            self._reader = None
        for sub in orphans:
            sub.offer(CLOSED)

    async def _release_connection_locked(self) -> None:
        pubsub, client = self._pubsub, self._client
        self._pubsub = self._client = None
        self._pending_unsubscribe.clear()
        for closeable in (pubsub, client):
            if closeable is None:
                continue
            try:
                await closeable.aclose()
            except Exception:
                # The socket is being discarded either way, and a failure to
                # close one that is already broken is not actionable.
                logger.debug("live_fanout: close failed", exc_info=True)

    def _forget(self, sub: Subscription) -> bool:
        """Drop one subscriber; True when its channel now has none left."""
        subscribers = self._subscribers.get(sub.channel)
        if subscribers is None or sub not in subscribers:
            return False
        subscribers.discard(sub)
        if subscribers:
            return False
        del self._subscribers[sub.channel]
        return True

    # -- shutdown -----------------------------------------------------------

    async def aclose(self) -> None:
        """Tear the hub down: lifespan shutdown, and between tests."""
        reader = self._reader
        self._reader = None
        if reader is not None and reader is not asyncio.current_task():
            reader.cancel()
            with contextlib.suppress(asyncio.CancelledError):
                await reader
        async with self._lock:
            orphans = [sub for subs in self._subscribers.values() for sub in subs]
            self._subscribers.clear()
            await self._release_connection_locked()
        for sub in orphans:
            sub.offer(CLOSED)


def _as_text(value: Any) -> str:
    """Channel names arrive as bytes unless the client decodes responses."""
    if isinstance(value, bytes):
        return value.decode("utf-8", "replace")
    return "" if value is None else str(value)


_HUB: Optional[LiveFanout] = None
_HUB_LOOP: Optional[asyncio.AbstractEventLoop] = None


def fanout() -> LiveFanout:
    """The process's hub, built on first use.

    Keyed on the running loop as well: every primitive in here (the lock, the
    mailboxes, the reader task) belongs to the loop that created it, and a hub
    carried onto a second loop raises rather than misbehaving quietly. A web
    dyno has exactly one loop per worker process, so in production this is
    built once and the check never fires.
    """
    global _HUB, _HUB_LOOP

    loop = asyncio.get_running_loop()
    if _HUB is None or _HUB_LOOP is not loop:
        if _HUB is not None:
            logger.warning("live_fanout: rebuilding the hub on a new event loop")
        _HUB = LiveFanout()
        _HUB_LOOP = loop
    return _HUB


async def reset_fanout() -> None:
    """Close and forget the process hub."""
    global _HUB, _HUB_LOOP

    hub, _HUB, _HUB_LOOP = _HUB, None, None
    if hub is not None:
        await hub.aclose()
