import Foundation

@main struct WatchTelemetryChecks {
    static func main() throws {
        let now = Date(timeIntervalSince1970: 1_800_000_000)
        let epoch = UUID()
        let grant = WatchTelemetryGrant(epoch: epoch, validUntil: now.addingTimeInterval(3600))
        func record(_ time: Date? = nil) -> WatchTelemetryRecord {
            WatchTelemetryRecord(recordedAt: time ?? now, kind: .action, surface: .game, action: .refresh)
        }
        var queue = WatchTelemetryBuffer()
        queue.append(record(), now: now)
        precondition(queue.records.isEmpty, "No choice means no collection")
        queue.setPhoneGrant(grant, now: now)
        queue.append(record(), now: now)
        precondition(queue.records.isEmpty, "Phone grant cannot grant Watch consent")
        queue.setWatchConsent(true)
        queue.append(record(), now: now)
        precondition(queue.records.isEmpty, "Watch grant alone cannot grant phone consent")
        queue.setPhoneGrant(grant, now: now)
        let first = record()
        queue.append(first, now: now)
        queue.append(first, now: now)
        precondition(queue.records.count == 1, "A record ID cannot be queued twice")
        let batch = queue.batch(now: now)!
        queue.acknowledge([first.id], phoneEpoch: UUID(), watchEpoch: batch.watchEpoch)
        precondition(queue.records.count == 1, "Stale phone acknowledgement ignored")
        queue.acknowledge([first.id], phoneEpoch: epoch, watchEpoch: UUID())
        precondition(queue.records.count == 1, "Stale Watch acknowledgement ignored")
        queue.acknowledge([first.id], phoneEpoch: epoch, watchEpoch: batch.watchEpoch)
        precondition(queue.records.isEmpty)
        for _ in 0..<80 { queue.append(record(), now: now) }
        precondition(queue.records.count == 64)
        precondition(queue.batch(now: now)!.records.count == 12)
        let oldestRetained = queue.records[1].id
        queue.append(record(), now: now)
        precondition(queue.records.first!.id == oldestRetained, "Evict oldest first")
        let restored = WatchTelemetryBuffer.restore(try JSONEncoder().encode(queue), now: now)
        precondition(restored.records.count == 64)
        precondition(WatchTelemetryBuffer.restore(Data(repeating: 0, count: 49153), now: now).records.isEmpty)
        precondition(WatchTelemetryBuffer.restore(Data("invalid".utf8), now: now).watchEpoch == nil)
        queue.setPhoneGrant(WatchTelemetryGrant(epoch: UUID(), validUntil: now.addingTimeInterval(3600)), now: now)
        precondition(queue.records.isEmpty, "Phone revoke/regrant epoch cannot replay old events")
        queue.append(record(), now: now)
        queue.setWatchConsent(false)
        precondition(queue.records.isEmpty && queue.watchEpoch == nil && queue.phoneGrant == nil)
        queue.setWatchConsent(true)
        queue.append(record(), now: now)
        precondition(queue.records.isEmpty, "Regrant requires fresh phone authority")
        queue.setPhoneGrant(grant, now: now)
        queue.append(record(now.addingTimeInterval(1)), now: now)
        queue.append(record(now.addingTimeInterval(-86400)), now: now)
        precondition(queue.records.isEmpty, "Future and expired records rejected")
        queue.append(record(), now: now)
        precondition(queue.batch(now: now.addingTimeInterval(3600)) == nil, "Expired grant drops buffer")
        queue.setPhoneGrant(WatchTelemetryGrant(epoch: epoch, validUntil: now.addingTimeInterval(86401)), now: now)
        precondition(queue.phoneGrant == nil, "Unbounded grant rejected")
        precondition(!WatchTelemetryRecord(recordedAt: now, kind: .refresh, surface: .game,
                                          outcome: .success, durationMS: -1).isWellFormed)
        precondition(!WatchTelemetryRecord(recordedAt: now, kind: .action, surface: .game).isWellFormed)
        precondition(!WatchTelemetryRecord(recordedAt: now, kind: .screen, surface: .game,
                                          action: .refresh).isWellFormed)
        let unknown = WatchTelemetryRecord(recordedAt: now, kind: .timing, surface: .picker,
                                           outcome: .empty, firstCardMS: -1, cold: true)
        precondition(unknown.isWellFormed, "Unknown first card remains -1, not a fabricated zero")
        queue.setPhoneGrant(grant, now: now)
        let submitted = record()
        queue.append(submitted, now: now)
        let wire = try JSONEncoder().encode(queue.batch(now: now)!)
        precondition(WatchTelemetryIngress.accept(wire, phoneEpoch: nil, now: now, seen: []).records.isEmpty)
        precondition(WatchTelemetryIngress.accept(wire, phoneEpoch: UUID(), now: now, seen: []).records.isEmpty)
        let accepted = WatchTelemetryIngress.accept(wire, phoneEpoch: epoch, now: now, seen: [])
        precondition(accepted.records.count == 1 && accepted.acknowledgement == [submitted.id])
        let replay = WatchTelemetryIngress.accept(wire, phoneEpoch: epoch, now: now, seen: [submitted.id])
        precondition(replay.records.isEmpty && replay.acknowledgement == [submitted.id])
        precondition(WatchTelemetryIngress.accept(wire, phoneEpoch: epoch, now: now.addingTimeInterval(86400), seen: []).records.isEmpty)
        precondition(WatchTelemetryIngress.accept(Data(repeating: 0, count: 12289), phoneEpoch: epoch, now: now, seen: []).records.isEmpty)
        let parameters = submitted.analyticsParameters
        precondition(parameters["device_class"] as? String == "watch")
        precondition(parameters["surface"] as? String == "watch_game")
        precondition(parameters["id"] == nil && parameters["recordedAt"] == nil && parameters["phoneEpoch"] == nil)
        print("WATCH_TELEMETRY_BUFFER=PASS deny/local+phone consent/revocation/regrant/ack/bounds/restore/expiry/schema")
    }
}
