/**
 * UX-P164 — the market page and search stop printing "Other 100%", for Alex's eyeball.
 *
 * ═══ WHAT A READER SEES TODAY ═══
 *
 * Read on the deployed build, 2026-08-29, both within a minute:
 *
 *     GET /api/futures/112903                    Democratic Party 85.5% · Republican Party 14.5% · Other 100%
 *     GET /api/events/search?q=which party...    Democratic Party 85.5% · Republican Party 14.5% · Other 100%
 *
 * "Other" is a no-bid ask — measured bid 0.0000 / ask 1.0000 (gotcha #17/#19) — on a
 * market whose real book is an 85.5/14.5 two-way. It prints as a 100% row sitting
 * underneath two real answers, on a US House election market.
 *
 * This is #993's OPENING SENTENCE, verbatim: "the futures DETAIL page showed
 * 'Other 100%'". Search was fixed then; the detail page was not, and the shared
 * module written to stop them diverging still let them agree on the wrong answer.
 *
 * ═══ WHY DEMOTION WAS NOT ENOUGH (and why this is not a re-litigation) ═══
 *
 * `display_rank_order` DEMOTES a dominant field row to the end rather than deleting
 * it. That is deliberate, pinned by `test_other_at_100_leaves_the_top_n`, and
 * UNCHANGED here. Demotion keeps the row out of a top-N slot only while the list is
 * LONGER than N — and neither of these surfaces is: the detail page renders the
 * whole list, and search has already sliced to `limit`. On a three-row market "the
 * end" is still on the page.
 *
 * ═══ WHAT EVERY PANEL IS MADE OF ═══
 *
 * Both arms are the SHIPPED components with the app's own compiled stylesheet.
 * `FuturesCard` is what `/search` renders (app/search/page.tsx:11) and it maps
 * `top_outcomes` through `OutcomeRow` — so the "Other 100%" row is a real render,
 * not a drawing. `FuturesHero` is the market page's headline.
 *
 * Neither payload is hand-written: `backend/tests/fixtures/uxp164_house_112903_detail.json`
 * was generated by running the real `app.utils.outcome_display` helpers over the DB
 * rows, and its `before` block reproduces both live payloads byte for byte.
 *
 *   UX_CAPTURE_DIR=<dir> TZ=UTC npx jest --testPathPatterns=detailOtherHundredCapture
 *
 * With no env var set it is an ordinary test that renders every panel and asserts
 * the rig works, same as the sibling capture rigs.
 */

import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import fs from "node:fs";
import path from "node:path";

jest.mock("next/navigation", () => ({
  __esModule: true,
  useRouter: () => ({ push: jest.fn(), replace: jest.fn(), prefetch: jest.fn() }),
}));
jest.mock("next/link", () => ({
  __esModule: true,
  default: ({ href, children }: { href: string; children: React.ReactNode }) => (
    <a href={href}>{children}</a>
  ),
}));
jest.mock("next/image", () => ({
  __esModule: true,
  default: ({ alt }: { alt: string }) => <img alt={alt} />,
}));
jest.mock("@/components/Analytics", () => ({
  __esModule: true,
  useAnalyticsContext: () => ({ track: () => {} }),
}));

import FuturesCard from "../../components/FuturesCard";
import { FuturesHero } from "../../components/FuturesHero";

const FRONTEND = path.join(__dirname, "..", "..");
const REPO = path.join(FRONTEND, "..");
const FIXTURE = path.join(
  REPO,
  "backend",
  "tests",
  "fixtures",
  "uxp164_house_112903_detail.json",
);

type Row = { id: number; name: string; probability: number | null; movement: number | null };
type Arm = { outcomes: Row[]; outcome_count: number };
type Fixture = {
  _source: string;
  market: Record<string, unknown>;
  db_rows: Row[];
  before: Arm;
  after: Arm;
};

function fixture(): Fixture {
  return JSON.parse(fs.readFileSync(FIXTURE, "utf8"));
}

/** The app's own compiled stylesheet, so the panels look like the product. */
function appStylesheet(): string {
  const dir = path.join(FRONTEND, ".next", "static", "css");
  try {
    return fs
      .readdirSync(dir)
      .filter((f) => f.endsWith(".css"))
      .map((f) => fs.readFileSync(path.join(dir, f), "utf8"))
      .join("\n");
  } catch {
    return "";
  }
}

/** The market as `/search` receives it. */
function asMarket(arm: Arm) {
  return {
    id: 112903,
    name: "Which party will win the House in 2026?",
    llm_sport_category: "politics",
    sport_name: "Politics",
    status: "open",
    source: "polymarket",
    source_count: 1,
    resolution_date: "2026-11-03T00:00:00Z",
    outcome_count: arm.outcome_count,
    top_outcomes: arm.outcomes.map((o) => ({ ...o, rank: null })),
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any;
}

/**
 * `renderToStaticMarkup` HTML-escapes, and the extractor must undo that before
 * reading copy back (UX-P046's `&lt;1%` sentinel trap, inherited).
 */
function visibleText(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&")
    .replace(/&#x27;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, " ")
    .trim();
}

function renderSearchCard(arm: Arm): string {
  return renderToStaticMarkup(<FuturesCard market={asMarket(arm)} />);
}

function renderHero(arm: Arm): string {
  const leader = arm.outcomes[0];
  return renderToStaticMarkup(
    <FuturesHero
      name="Which party will win the House in 2026?"
      probability={leader.probability ?? null}
      outcomeName={leader.name}
      sourceCount={1}
      categoryEmoji="🏛️"
      categoryLabel="Politics"
      isMultiOutcome={arm.outcome_count > 2}
    />,
  );
}

describe("UX-P164 — 'Other 100%' leaves the market page and search", () => {
  const fx = fixture();

  it("the fixture reproduces what production served", () => {
    expect(fx.before.outcomes.map((o) => [o.name, o.probability])).toEqual([
      ["Democratic Party", 0.855],
      ["Republican Party", 0.145],
      ["Other", 1.0],
    ]);
  });

  it("BEFORE: the shipped search card prints an Other row at 100%", () => {
    const text = visibleText(renderSearchCard(fx.before));
    expect(text).toContain("Other");
    expect(text).toMatch(/100\s*%/);
  });

  it("AFTER: the Other row is gone and the two real answers are untouched", () => {
    const text = visibleText(renderSearchCard(fx.after));
    expect(text).not.toContain("Other");
    expect(text).not.toMatch(/100\s*%/);
    expect(text).toContain("Democratic Party");
    expect(text).toContain("Republican Party");
  });

  it("AFTER: the leader still prints 86%, the book price, unrestated", () => {
    // The drop narrows WHAT IS SHOWN. It must not move either surviving number —
    // 0.855 half-up to 86% is what the market page has served all along.
    const text = visibleText(renderSearchCard(fx.after));
    expect(text).toMatch(/86\s*%/);
    expect(visibleText(renderSearchCard(fx.before))).toMatch(/86\s*%/);
  });

  it("the hero's two-segment bar appears only once the market is a real two-way", () => {
    // `outcome_count` 3 -> 2 flips `isMultiOutcome`, which gates the Yes/No bar
    // (FuturesHero.tsx:151). That is the one API-contract consequence of the drop,
    // and it renders CORRECTLY: on an 85.5/14.5 two-way the muted remainder IS the
    // Republican share, so the bar is honest rather than newly wrong.
    const before = renderHero(fx.before);
    const after = renderHero(fx.after);
    const bar = /class="flex h-\[9px\] gap-0\.5 mb-2"/;
    expect(before).not.toMatch(bar);
    expect(after).toMatch(bar);
  });

  it("writes the artifact when asked", () => {
    const dir = process.env.UX_CAPTURE_DIR;
    const panels = [
      ["BEFORE — /search card, as deployed", renderSearchCard(fx.before)],
      ["AFTER — /search card, this branch", renderSearchCard(fx.after)],
      ["BEFORE — market-page hero", renderHero(fx.before)],
      ["AFTER — market-page hero", renderHero(fx.after)],
    ];
    // The rig asserts its own artifact even when it is not writing one.
    panels.forEach(([, html]) => expect(html.length).toBeGreaterThan(200));
    if (!dir) return;
    fs.mkdirSync(dir, { recursive: true });
    const html = `<!doctype html><meta charset="utf-8">
<title>UX-P164 — "Other 100%" leaves the market page and search</title>
<style>${appStylesheet()}
body{background:#f6f7f9;font-family:ui-sans-serif,system-ui,sans-serif;padding:28px;margin:0}
h1{font-size:19px;margin:0 0 6px}
p.lede{font-size:13px;color:#475569;max-width:76ch;margin:0 0 20px;line-height:1.55}
.grid{display:grid;grid-template-columns:repeat(2,minmax(320px,1fr));gap:18px;max-width:1000px}
.panel{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:14px}
.cap{font-size:11px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;color:#64748b;margin-bottom:10px}
</style>
<h1>UX-P164 — "Other 100%" leaves the market page and search</h1>
<p class="lede">Market 112903, "Which party will win the House in 2026?". On 2026-08-29 both
<code>/api/futures/112903</code> and <code>/api/events/search</code> served a third row —
<strong>Other 100%</strong> — under two real answers. It is a no-bid ask (bid 0.0000 / ask 1.0000),
not an answer. Demotion could not help: it moves the row to "the end", and on a three-row market the
end is still on the page. Every panel is the shipped component; the payloads come from
<code>uxp164_house_112903_detail.json</code>, whose BEFORE block reproduces both live payloads exactly.</p>
<div class="grid">
${panels.map(([cap, h]) => `<div class="panel"><div class="cap">${cap}</div>${h}</div>`).join("\n")}
</div>`;
    fs.writeFileSync(path.join(dir, "ux-p164-other-hundred.html"), html);
    expect(fs.existsSync(path.join(dir, "ux-p164-other-hundred.html"))).toBe(true);
  });
});
