/**
 * UX-P163 — Discover stops halving a market's price, for Alex's eyeball.
 *
 * ═══ WHAT A READER SEES TODAY ═══
 *
 * `GET /api/feed` and `GET /api/futures/112903`, read within a minute of each other
 * on 2026-08-29, disagreed by FORTY-THREE POINTS about the same market:
 *
 *     Discover        Democratic Party  43%
 *     Market page     Democratic Party  85.5%
 *
 * Not a rounding drift — a halving. UX-P162 closed this class at the one-point
 * level; this is the same class at the point where it is impossible to miss.
 *
 * ═══ WHY (each step correct, the composition not) ═══
 *
 * The market holds 9 outcomes. Six are anonymized reserved slots ("Party A".."Party
 * F") priced 1.0, which `display_rank_order` DROPS. A seventh 1.0 row is named
 * "Other" — a field outcome, not a placeholder — so it is DEMOTED to the end
 * instead, which is the deliberate, tested contract. Three rows then remain, so
 * "the end" is still inside a `[:3]` card, and those three sum to exactly 2.0: the
 * inclusive top of `_feed_display_scale`'s band. Divisor 2.0, everything halved.
 *
 * The filter that made the card MORE honest is what pulled it into the scaling
 * regime that made it less so. With the six placeholders still present the sum is
 * ~8.0, above the band, and nothing would have been scaled at all.
 *
 * ═══ WHAT EVERY PANEL IS MADE OF ═══
 *
 * Both cards are the SHIPPED components with the app's own compiled stylesheet.
 * Neither payload is drawn by hand: `backend/tests/fixtures/uxp163_house_112903.json`
 * carries the DB rows, the BEFORE block (which reproduces the live feed byte for
 * byte) and the AFTER block, all three generated by running the real serializer
 * helpers over the real prices.
 *
 *   UX_CAPTURE_DIR=<dir> TZ=UTC npx jest --testPathPatterns=houseCardHalvingCapture
 *
 * With no env var set it is an ordinary test that renders every panel and asserts
 * the rig works, same as the sibling capture rigs.
 */

import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import fs from "node:fs";
import path from "node:path";
import type { FeedItem, FeedFuturesData } from "@/lib/types";

jest.mock("next/navigation", () => ({
  __esModule: true,
  useRouter: () => ({ push: jest.fn(), replace: jest.fn(), prefetch: jest.fn() }),
}));
jest.mock("next/link", () => ({
  __esModule: true,
  default: ({ href, children }: { href: string; children: React.ReactNode }) => (
    <a href={href}>{children}</a>
  ),
}));
jest.mock("next/image", () => ({
  __esModule: true,
  default: ({ alt }: { alt: string }) => <img alt={alt} />,
}));
jest.mock("@/components/Analytics", () => ({
  __esModule: true,
  useAnalyticsContext: () => ({ track: () => {} }),
}));

import FeedCard from "../../components/FeedCard";
import { FuturesCard } from "../../components/discover/FuturesCard";

const FRONTEND = path.join(__dirname, "..", "..");
const REPO = path.join(FRONTEND, "..");
const FIXTURE = path.join(
  REPO,
  "backend",
  "tests",
  "fixtures",
  "uxp163_house_112903.json",
);

type Served = {
  top_outcomes: Array<{
    id: number;
    name: string;
    probability: number | null;
    rank: number;
    rendered_percent: number | null;
  }>;
  card_sum_reason: string | null;
  display_scale: number;
};
type Fixture = {
  _provenance: Record<string, string | number>;
  db_outcomes: Array<{ id: number; name: string; current_probability: number | null }>;
  served_before: Served;
  served_after: Served;
};

function fixture(): Fixture {
  return JSON.parse(fs.readFileSync(FIXTURE, "utf8"));
}

/** The app's own compiled stylesheet, so the cards look like the product. */
function appStylesheet(): string {
  const dir = path.join(FRONTEND, ".next", "static", "css");
  try {
    return fs
      .readdirSync(dir)
      .filter((f) => f.endsWith(".css"))
      .map((f) => fs.readFileSync(path.join(dir, f), "utf8"))
      .join("\n");
  } catch {
    return "";
  }
}

/**
 * The card as the feed serves it. `outcome_count` stays 9 in BOTH arms: the raw
 * count is what the payload carries and the fix does not touch it, so a difference
 * here would be the rig editing the evidence.
 */
function asData(served: Served): FeedFuturesData {
  return {
    id: 112903,
    name: "Which party will win the House in 2026?",
    llm_sport_category: "politics",
    sport_name: "Politics",
    status: "open",
    source: "polymarket",
    source_count: 1,
    market_tier: 2,
    resolution_date: "2026-11-03T00:00:00Z",
    outcome_count: 9,
    group_type: "negrisk",
    top_outcomes: served.top_outcomes.map((o) => ({ movement: null, ...o })),
    card_sum_reason: served.card_sum_reason,
  } as unknown as FeedFuturesData;
}

function itemFor(data: FeedFuturesData): FeedItem {
  return {
    type: "futures",
    score: 76,
    reason: "",
    headline: "",
    data,
  } as unknown as FeedItem;
}

const HERO_RE = /(data-testid="futures-hero-probability"[^>]*>)([^<]+)(<)/;

function discoverHtml(data: FeedFuturesData): string {
  return renderToStaticMarkup(
    <FuturesCard
      item={itemFor(data)}
      data={data}
      liked={false}
      setLiked={() => {}}
      trending={false}
    />,
  );
}

function feedCardHtml(data: FeedFuturesData): string {
  return renderToStaticMarkup(<FeedCard item={itemFor(data)} />);
}

/**
 * UX-P046's sentinels come back HTML-escaped from `renderToStaticMarkup` (`&lt;1%`),
 * so anything comparing rendered text to a constant must unescape first or it fails
 * on the entity rather than on behaviour. Inherited trap, not a hypothetical.
 */
function unescape(s: string): string {
  return s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
}

function heroText(html: string): string | null {
  const m = html.match(HERO_RE);
  return m ? unescape(m[2]) : null;
}

/** Every whole percent the card prints, in document order. */
function printedPercents(html: string): string[] {
  return (html.match(/>(?:&lt;1%|&gt;99%|\d{1,3}%)</g) ?? []).map((m) =>
    unescape(m.slice(1, -1)),
  );
}

function bookRow(f: Fixture): string {
  const real = f.db_outcomes.filter((o) => !/^Party [A-Z]$/.test(o.name));
  return real
    .map((o) => `${o.name} <b>${o.current_probability}</b>`)
    .join(" &nbsp;·&nbsp; ");
}

function panelOne(f: Fixture): string {
  const before = asData(f.served_before);
  const after = asData(f.served_after);
  const beforeHtml = discoverHtml(before);
  const afterHtml = discoverHtml(after);
  return `<section>
  <h2>Panel 1 — the live card, before and after</h2>
  <p class="note">The book, from <code>futures_outcomes</code>: ${bookRow(f)}<br>
  <code>GET /api/futures/112903</code> served <b>0.855 / 0.145 / 1.0</b> at the same moment.</p>
  <p class="note bad">BEFORE, Discover headlined <b>${heroText(beforeHtml)}</b> for a party the
  book prices at <b>85.5%</b> — display scale <b>${f.served_before.display_scale}</b>, so every
  number the payload carries is halved.</p>
  <p class="note ok">AFTER, Discover headlines <b>${heroText(afterHtml)}</b> — display scale
  <b>${f.served_after.display_scale}</b>, and the two real parties total 100.</p>
  <p class="note">This market's <code>suggested_format</code> is <code>binary_probability</code>,
  so Discover draws the hero-only variant: the wrong number is the ONLY thing a Discover reader
  sees, with nothing else on the card to contradict it. The list — including the no-bid "Other"
  at 50% — is what <code>FeedCard</code> prints, in Panel 2.</p>
  <table>
    <thead><tr>
      <th>Discover — BEFORE (deployed)</th>
      <th>Discover — AFTER (this branch)</th>
    </tr></thead>
    <tbody><tr>
      <td class="col">${beforeHtml}</td>
      <td class="col">${afterHtml}</td>
    </tr></tbody>
  </table>
  <table>
    <thead><tr><th></th><th>Percents printed</th></tr></thead>
    <tbody>
      <tr><td class="name">BEFORE</td><td class="bad mono">${printedPercents(beforeHtml).join("  ")}</td></tr>
      <tr><td class="name">AFTER</td><td class="ok mono">${printedPercents(afterHtml).join("  ")}</td></tr>
    </tbody>
  </table>
</section>`;
}

function panelTwo(f: Fixture): string {
  const before = asData(f.served_before);
  const after = asData(f.served_after);
  return `<section>
  <h2>Panel 2 — the other surface moves with it</h2>
  <p class="note">The category pages, <code>/sports</code> and <code>/my-stuff</code> draw this
  same payload through <code>FeedCard</code>. The fix is in the serializer, so both surfaces
  move together — fixing one would have relocated the disagreement rather than ended it,
  which is UX-P162's lesson applied before it could bite.</p>
  <table>
    <thead><tr>
      <th>FeedCard — BEFORE (deployed)</th>
      <th>FeedCard — AFTER (this branch)</th>
    </tr></thead>
    <tbody><tr>
      <td class="col">${feedCardHtml(before)}</td>
      <td class="col">${feedCardHtml(after)}</td>
    </tr></tbody>
  </table>
</section>`;
}

function panelThree(f: Fixture): string {
  const rows = f.db_outcomes
    .map((o) => {
      const placeholder = /^Party [A-Z]$/.test(o.name);
      const field = /^Other$/i.test(o.name);
      const fate = placeholder
        ? ["dropped — anonymized reserved slot", "ok"]
        : field
          ? ["dropped — no-bid field row at 1.0 (was: demoted, still printed)", "ok"]
          : ["printed", ""];
      return `<tr><td class="name">${o.name}</td><td class="mono">${o.current_probability}</td><td class="${fate[1]}">${fate[0]}</td></tr>`;
    })
    .join("\n");
  return `<section>
  <h2>Panel 3 — what happens to each of the nine rows</h2>
  <p class="note">Six placeholders were already dropped and that is what pulled the surviving
  sum from ~8.0 down to exactly 2.0 — the inclusive top of the normalization band. The seventh
  1.0 row is the one this queue removes.</p>
  <table>
    <thead><tr><th>Outcome</th><th>Book price</th><th>Fate on the card</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</section>`;
}

function page(f: Fixture): string {
  return `<!doctype html>
<meta charset="utf-8">
<title>UX-P163 — Discover stops halving a market's price</title>
<style>${appStylesheet()}</style>
<style>
  body { font: 14px/1.5 -apple-system, system-ui, sans-serif; margin: 32px; background: #fff; color: #111; }
  h1 { font-size: 22px; } h2 { font-size: 16px; margin-top: 34px; }
  table { border-collapse: collapse; margin-top: 12px; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: #666; padding: 6px 10px; }
  td { vertical-align: top; padding: 10px; border-top: 1px solid #eee; }
  td.col { width: 360px; }
  td.name { width: 200px; font-size: 12px; }
  .mono { font-family: ui-monospace, monospace; }
  code, small { color: #777; font-family: ui-monospace, monospace; }
  .note { max-width: 820px; } .ok { color: #0a7d38; } .bad { color: #b4232c; }
</style>
<h1>UX-P163 — Discover stops halving a market's price</h1>
<p class="note">Measured on the deployed build 2026-08-29: Discover printed
<b>Democratic Party 43%</b> while the market page printed <b>85.5%</b> for the same question at
the same moment. A no-bid "Other" row, demoted but still on the card, sat in the divisor that
scales every number the card prints.</p>
${panelOne(f)}
${panelTwo(f)}
${panelThree(f)}
`;
}

describe("UX-P163 capture", () => {
  it("the fixture's BEFORE block is the payload production actually served", () => {
    const f = fixture();
    expect(f.served_before.top_outcomes.map((o) => o.probability)).toEqual([
      0.4275, 0.0725, 0.5,
    ]);
    expect(f.served_before.display_scale).toBe(2.0);
  });

  it("Discover headlines 43% before and 86% after", () => {
    const f = fixture();
    expect(heroText(discoverHtml(asData(f.served_before)))).toBe("43%");
    expect(heroText(discoverHtml(asData(f.served_after)))).toBe("86%");
  });

  it("the untradeable row is gone from the LIST surface, not renumbered", () => {
    // Scoped to `FeedCard` deliberately. This market's `suggested_format` is
    // `binary_probability`, so Discover draws the hero-only variant and never
    // prints the outcome list — asserting "Other" against the Discover markup
    // would pass for the wrong reason (absent in both arms).
    const f = fixture();
    expect(feedCardHtml(asData(f.served_before))).toContain("Other");
    expect(feedCardHtml(asData(f.served_after))).not.toContain("Other");
  });

  it("the category-page surface moves with Discover", () => {
    const f = fixture();
    expect(feedCardHtml(asData(f.served_before))).toContain("43%");
    expect(feedCardHtml(asData(f.served_after))).toContain("86%");
  });

  it("renders the page, and writes it when UX_CAPTURE_DIR is set", () => {
    const html = page(fixture());
    expect(html).toContain("Panel 1");
    expect(html).toContain("Panel 2");
    expect(html).toContain("Panel 3");
    const dir = process.env.UX_CAPTURE_DIR;
    if (dir) {
      fs.mkdirSync(dir, { recursive: true });
      const out = path.join(dir, "ux-p163-house-card-halving.html");
      fs.writeFileSync(out, html, "utf8");
      // eslint-disable-next-line no-console
      console.log(`capture written: ${out}`);
    }
  });
});
