/**
 * UX-P175 — THE CHAMPIONSHIP GRID STOPS DISCARDING EVERY HONEST SIGNAL THE
 * SERVER SENDS IT.
 *
 * ═══ WHAT THIS IS ═══
 *
 * `/api/playoffs/{slug}` goes to real trouble to be honest about its own
 * failures, and `/playoffs/[sport]` threw all three signals away.
 *
 *   1. On a 503 the route says WHY:
 *
 *        "Playoff grid for 'la-liga' timed out and no last-good payload is
 *         available. This is a degraded state, not an empty league."
 *
 *      That last clause is deliberate: it stops a reader concluding the
 *      competition has no markets — the same false claim UX-P173 removed from
 *      the empty state. `apiFetch` preserves it on purpose (`lib/api.ts:154`:
 *      "that's what lets a page render an honest state rather than a generic
 *      'Failed to load'"). The page rendered "Failed to load championship grid.
 *      Please try again." anyway.
 *
 *   2. #1484 labels a last-good serve `degraded: true` when the live rebuild
 *      FAILED, specifically so consumers stop reading substituted old numbers
 *      as this minute's build. The page read neither `degraded` nor
 *      `degraded_reason`, so a degraded grid rendered identically to a fresh
 *      one — confidently, with a 60s refresh, and no timestamp anywhere.
 *
 *   3. The same mechanism labels a ROUTINE between-warms serve `stale: true`
 *      with `degraded` absent. `_mark_last_good`'s docstring is explicit that
 *      these two must not share a severity, because treating routine staleness
 *      as failure "would fire RED on three healthy grids every deploy".
 *
 * ═══ THE READER COUNT (measured 2026-08-29) ═══
 *
 * Sentry, backend project, 14-day window, verified against a nonsense-query
 * control that returned 0:
 *
 *     9  x 503 raised -> reader saw the generic "Failed to load"
 *        across 6 of the 14 slugs: ncaa-basketball 2, ncaa-football 2, mls 2,
 *        golf 1, ncaa-women-basketball 1, epl 1
 *        7 of the 9 landed on 2026-08-29 alone; still firing at 17:37 that day
 *    10  x "timed out ... attempting last-good" logged
 *        ncaa-basketball: 10 logged vs 7 raised, so 3 were rescued by a
 *        last-good payload and served as degraded 200s — rendered as fresh
 *
 * And one production sweep of all 14 slugs, one request each, spaced 1.3s:
 *
 *     5 of 14 were serving `stale: true` at that moment
 *       (nfl, mls, ncaa-basketball, epl, bundesliga)
 *
 * WHO: every reader of `/playoffs/[sport]`. `LeagueTabs` repeats all 14
 * destinations on every grid page, so each is one tap from every other.
 *
 * ═══ WHAT EVERY FIXTURE HERE IS MADE OF ═══
 *
 * Nothing here is hand-written, because a hardcoded fixture is what let
 * CERT-433 through: it stays green when someone deletes the producer.
 *
 *   uxp175_playoffs_503_detail.json   generated by calling the shipped
 *                                     `degraded_grid_detail()` — the same
 *                                     function the route raises with.
 *   uxp175_playoffs_nba_control.json  verbatim production `/api/playoffs/nba`.
 *   uxp175_playoffs_nba_degraded.json THAT payload passed through the shipped
 *                                     `_mark_last_good(..., "timeout",
 *                                     degraded=True)`. Control and degraded
 *                                     therefore differ in exactly the four keys
 *                                     the producer adds, and nothing else.
 *   uxp175_playoffs_epl_stale.json    verbatim production `/api/playoffs/epl`,
 *                                     which production had ALREADY stamped
 *                                     `stale/cache_miss` — a real routine
 *                                     last-good serve, not a simulated one.
 *
 * `backend/tests/test_playoff_degraded_contract.py` fails if any of these drift
 * from what the backend now produces, so the two layers read one source rather
 * than agreeing from two.
 *
 * Every panel is the shipped `app/playoffs/[sport]/page.tsx`.
 */

import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

import DETAIL_503 from "../fixtures/uxp175_playoffs_503_detail.json";
import SERVED_CONTROL from "../fixtures/uxp175_playoffs_nba_control.json";
import SERVED_DEGRADED from "../fixtures/uxp175_playoffs_nba_degraded.json";
import SERVED_STALE from "../fixtures/uxp175_playoffs_epl_stale.json";

const GENERIC = "Failed to load championship grid";
const DEGRADED_HEADLINE = "These odds are from an earlier build";

let gridPayload: unknown;
let gridError: unknown;

jest.mock("swr", () => ({
  __esModule: true,
  default: (key: unknown) => ({
    // The page holds two SWR calls: the grid, and a golf-only schedule keyed
    // `null` for every other league. Only the grid must resolve.
    data: key === null ? undefined : gridPayload,
    error: key === null ? undefined : gridError,
    isLoading: false,
    mutate: () => undefined,
  }),
}));

jest.mock("@/hooks", () => ({
  __esModule: true,
  usePageTracking: () => undefined,
  useScrollDepth: () => undefined,
  useEngagementTime: () => undefined,
}));

let currentSlug = "nba";

jest.mock("next/navigation", () => ({
  __esModule: true,
  useRouter: () => ({ push: () => {}, replace: () => {}, prefetch: () => {} }),
  usePathname: () => `/playoffs/${currentSlug}`,
  useSearchParams: () => new URLSearchParams(),
  useParams: () => ({ sport: currentSlug }),
}));

// eslint-disable-next-line @typescript-eslint/no-var-requires
const PlayoffGridPage = require("@/app/playoffs/[sport]/page").default;
// eslint-disable-next-line @typescript-eslint/no-var-requires
const { AnalyticsProvider } = require("@/components/Analytics");

/**
 * The progression table calls `useAnalyticsContext`, which throws outside the
 * provider. Wrap in the REAL `AnalyticsProvider` — the one `app/layout.tsx`
 * uses — so what renders is what ships, not the page with its chrome removed.
 */
function render(
  payload: unknown,
  opts: { error?: unknown; slug?: string } = {}
): string {
  gridPayload = payload;
  gridError = opts.error;
  currentSlug = opts.slug ?? "nba";
  return renderToStaticMarkup(
    React.createElement(
      AnalyticsProvider,
      null,
      React.createElement(PlayoffGridPage, { params: { sport: currentSlug } })
    )
  );
}

/** Strip tags so assertions read what a PERSON reads, not what React emitted. */
function visibleText(markup: string): string {
  return markup
    .replace(/<[^>]*>/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#x27;|&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&middot;/g, "·")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Build the error object `apiFetch` actually throws (lib/api.ts:169-172). */
function apiError(status: number, detail?: unknown): Error {
  const message =
    typeof detail === "string" && detail ? detail : `API error: ${status}`;
  const e = new Error(message) as Error & {
    status?: number;
    detail?: unknown;
  };
  e.status = status;
  e.detail = detail;
  return e;
}

describe("the 503 — the page stops overwriting the server's reason", () => {
  it("renders the server's own sentence, not the generic line", () => {
    const text = visibleText(
      render(undefined, { error: apiError(503, DETAIL_503.detail), slug: "la-liga" })
    );
    expect(text).toContain(DETAIL_503.detail);
    expect(text).not.toContain(GENERIC);
  });

  it("keeps the clause that stops the reader blaming the league", () => {
    // This is the whole point of preferring the server's wording. If the
    // sentence ever loses this clause the page silently goes back to implying
    // an empty competition.
    const text = visibleText(
      render(undefined, { error: apiError(503, DETAIL_503.detail), slug: "la-liga" })
    );
    expect(text).toContain("not an empty league");
    expect(text).not.toContain("No championship odds available yet");
  });

  it("CONTROL — falls back to the generic line when the server sent no reason", () => {
    // A 500 with no `detail` makes `apiFetch` synthesize "API error: 500".
    // Showing a reader a bare status code is worse than the generic line, so
    // the fix keys on `detail`, not on `message`. Without this control a rule
    // of "always print error.message" would pass the test above and ship
    // "API error: 500" to production.
    const text = visibleText(
      render(undefined, { error: apiError(500), slug: "ncaa-women-basketball" })
    );
    expect(text).toContain(GENERIC);
    expect(text).not.toContain("API error: 500");
  });

  it("CONTROL — a non-string detail never reaches the reader as [object Object]", () => {
    const text = visibleText(
      render(undefined, { error: apiError(503, { code: "timeout" }) })
    );
    expect(text).toContain(GENERIC);
    expect(text).not.toContain("[object Object]");
  });
});

describe("the degraded serve — old numbers stop passing as this minute's", () => {
  it("the fixture differs from the control in exactly the producer's four keys", () => {
    const delta = Object.keys(SERVED_DEGRADED).filter(
      (k) => !(k in SERVED_CONTROL)
    );
    expect(delta.sort()).toEqual([
      "degraded",
      "degraded_reason",
      "stale",
      "stale_reason",
    ]);
    expect(SERVED_DEGRADED.degraded).toBe(true);
    expect(SERVED_DEGRADED.degraded_reason).toBe("timeout");
  });

  it("says so, in words, above the grid", () => {
    const text = visibleText(render(SERVED_DEGRADED));
    expect(text).toContain(DEGRADED_HEADLINE);
    expect(text).toContain("did not finish");
  });

  it("still shows the grid — degraded is not absent", () => {
    // The distinction that matters: a 503 has no numbers to show, a degraded
    // serve has real ones that are merely old. Blanking the grid here would be
    // a different lie.
    const text = visibleText(render(SERVED_DEGRADED));
    expect(text).toContain("30 teams");
  });

  it("dates the numbers it is asking the reader to distrust", () => {
    const text = visibleText(render(SERVED_DEGRADED));
    expect(text).toMatch(/\w{3} \d+, \d{2}:\d{2} UTC/);
  });

  it("CONTROL — the identical payload without the flags shows no notice", () => {
    // Control and degraded are the same production body; only the producer's
    // four keys differ. A rule that darkened every grid would pass every
    // assertion above and fail here.
    const text = visibleText(render(SERVED_CONTROL));
    expect(text).not.toContain(DEGRADED_HEADLINE);
    expect(text).toContain("30 teams");
  });
});

describe("the routine stale serve — a timestamp, deliberately not an alarm", () => {
  it("is a real production last-good serve, not a simulated one", () => {
    expect(SERVED_STALE.stale).toBe(true);
    expect(SERVED_STALE.stale_reason).toBe("cache_miss");
    expect("degraded" in SERVED_STALE).toBe(false);
  });

  it("dates the grid in the footer", () => {
    const text = visibleText(render(SERVED_STALE, { slug: "epl" }));
    expect(text).toMatch(/as of \w{3} \d+, \d{2}:\d{2} UTC/);
  });

  it("does NOT cry wolf — no degraded notice on a healthy between-warms serve", () => {
    // `_mark_last_good`'s docstring: treating an ordinary between-warms serve
    // as a failure "would fire RED on three healthy grids every deploy".
    // 5 of 14 grids carried this flag in a single sweep.
    const text = visibleText(render(SERVED_STALE, { slug: "epl" }));
    expect(text).not.toContain(DEGRADED_HEADLINE);
  });

  it("CONTROL — a fresh payload carries no timestamp at all", () => {
    const text = visibleText(render(SERVED_CONTROL));
    expect(text).not.toContain("as of ");
  });
});

describe("the timestamp is timezone-pinned", () => {
  /**
   * ⚠️ THIS SUITE MUST BE RUN UNDER A NON-UTC `TZ` TO MEAN ANYTHING.
   *
   * An unpinned `toLocaleString` renders in the runtime's zone, which under
   * CI's `TZ=UTC` is byte-identical to a correct pin. The first version of this
   * test swapped `process.env.TZ` inside the test and compared the results —
   * it passed, and then SURVIVED the mutation that deletes `timeZone: "UTC"`,
   * because jest has already warmed V8's zone cache by the time a test body
   * runs and reassigning `process.env.TZ` mid-process does not invalidate it.
   * (In a fresh `node -e` process the same reassignment works, which is exactly
   * how a vacuous test like that hides.)
   *
   * So: assert a FIXED expected literal instead. Under `TZ=UTC` this is green
   * either way; under `TZ=America/Los_Angeles` an unpinned render reads
   * "Aug 29, 10:28" and this fails. `artifacts-ux-p175/mutate.py` runs the
   * suite under both zones and requires the deletion to go red.
   */
  const ISO_TO_STAMP: [string, string][] = [
    // last_updated of each fixture -> what a reader must see, in every zone.
    ["2026-08-29T17:28:20.549552+00:00", "Aug 29, 17:28 UTC"],
    ["2026-08-29T14:56:21.249090+00:00", "Aug 29, 14:56 UTC"],
  ];

  it("the degraded grid's stamp is the fixture's time expressed in UTC", () => {
    expect(SERVED_DEGRADED.last_updated).toBe(ISO_TO_STAMP[0][0]);
    const text = visibleText(render(SERVED_DEGRADED));
    expect(text).toContain(ISO_TO_STAMP[0][1]);
  });

  it("the stale grid's footer stamp is the fixture's time expressed in UTC", () => {
    expect(SERVED_STALE.last_updated).toBe(ISO_TO_STAMP[1][0]);
    const text = visibleText(render(SERVED_STALE, { slug: "epl" }));
    expect(text).toContain(`as of ${ISO_TO_STAMP[1][1]}`);
  });

  it("names its zone, so the number is never ambiguous to a reader", () => {
    const text = visibleText(render(SERVED_DEGRADED));
    expect(text).toMatch(/\d{2}:\d{2} UTC/);
  });
});

describe("the artifact", () => {
  it("writes a render of all four states that asserts its own content", () => {
    const err = render(undefined, {
      error: apiError(503, DETAIL_503.detail),
      slug: "la-liga",
    });
    const degraded = render(SERVED_DEGRADED);
    const stale = render(SERVED_STALE, { slug: "epl" });
    const control = render(SERVED_CONTROL);

    // The rig refuses to emit a file that does not show the defect and its fix.
    expect(visibleText(err)).toContain("not an empty league");
    expect(visibleText(err)).not.toContain(GENERIC);
    expect(visibleText(degraded)).toContain(DEGRADED_HEADLINE);
    expect(visibleText(stale)).toContain("as of ");
    expect(visibleText(stale)).not.toContain(DEGRADED_HEADLINE);
    expect(visibleText(control)).not.toContain(DEGRADED_HEADLINE);
    expect(visibleText(control)).not.toContain("as of ");

    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const fs = require("fs");
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const path = require("path");
    const out = process.env.UXP175_ARTIFACT_DIR;
    if (!out) return; // opt-in; the assertions above are the gate
    fs.mkdirSync(out, { recursive: true });
    const panel = (h: string, sub: string, body: string) =>
      `<h2 style="font:600 15px system-ui;margin-top:28px">${h}</h2>
<p style="color:#666;font:13px system-ui;max-width:78ch;margin:4px 0 8px">${sub}</p>
<div style="border:1px solid #ddd;padding:16px;border-radius:8px">${body}</div>`;
    fs.writeFileSync(
      path.join(out, "playoffs-degraded-states.html"),
      `<!doctype html><meta charset="utf-8">
<title>UX-P175 — /playoffs/[sport] honest degradation</title>
<body style="font-family:system-ui;margin:0;padding:24px;background:#fff">
<h1 style="font:600 18px system-ui">UX-P175 — <code>/playoffs/[sport]</code> stops discarding the server's honesty</h1>
<p style="color:#666;font:14px system-ui;max-width:78ch">
Every panel is the shipped <code>app/playoffs/[sport]/page.tsx</code>. The 503 sentence
is generated by the shipped <code>degraded_grid_detail()</code>; the degraded payload is
verbatim production <code>/api/playoffs/nba</code> passed through the shipped
<code>_mark_last_good(..., "timeout", degraded=True)</code>; the stale payload is verbatim
production <code>/api/playoffs/epl</code>, which production had already stamped
<code>cache_miss</code>. Measured 2026-08-29: 9 reader-visible 503s over 14 days across 6 of
14 slugs, and 5 of 14 grids serving <code>stale</code> in one sweep.</p>
${panel(
  "503 — was: &ldquo;Failed to load championship grid.&rdquo;",
  "Now the route's own sentence, including the clause that stops a reader concluding the league has no markets.",
  err
)}
${panel(
  "degraded: true — was: indistinguishable from a fresh grid",
  "The live rebuild failed and these are substituted old numbers. The grid still shows, because degraded is not absent.",
  degraded
)}
${panel(
  "stale: true (cache_miss) — routine",
  "A timestamp in the footer and no alarm. 5 of 14 grids carried this flag in one sweep; anything louder would cry wolf.",
  stale
)}
${panel(
  "CONTROL — the same production payload, no flags",
  "No notice, no timestamp. A rule that darkened every grid would fail here.",
  control
)}
</body>`
    );
  });
});
