/**
 * CAPTURE RIG — the BRACKET TAB, at phone width.
 *
 * Chromium is dead in this sandbox (Mach bootstrap denied), so a screenshot is
 * not available to this lane. This is the substitute the repo already uses:
 * render the ACTUAL shipped component with `renderToStaticMarkup`, wrap it in
 * the app's OWN compiled stylesheet from `.next/static/css`, and write a
 * self-contained HTML file. Real component, real CSS — not a re-creation.
 *
 * ═══ WHAT UX-P139 CHANGED ABOUT THIS RIG ═══
 *
 * UX-P138's version BUILT the grid here, in the test, out of a board, a slate
 * and a props file — because that is where the grid was built in production
 * too. Alex's amendment moved that build to the server ("the grid reads only
 * the register"), and this rig follows: it reads
 * `docs/mocks/us-open/payload-2026-08-27.json`, which is the route's OWN
 * output over the committed register and a bounded production price read.
 *
 * That is a strictly better artifact. Every number in it came through the same
 * code path Alex will hit, including the two evals, so the panels cannot
 * flatter the design by assembling the grid more carefully than production
 * does.
 *
 * The synthetic second-week panels are GONE for the same reason. They existed
 * because the real grid was sparse and the design could not be judged on it;
 * the real grid is now 212 of 280 cells priced with a complete four-round
 * ladder for every player who has one, so the real data shows the design.
 *
 * Two jobs, and the second is why it lives under `__tests__`:
 *
 *   1. `UX_CAPTURE_DIR=<dir> npx jest --testPathPatterns=usOpenBracketCapture`
 *      writes `us-open-bracket.html`, every state at a 390px viewport.
 *   2. With no env var set it is an ordinary test that renders each state and
 *      asserts the rig still works — a capture harness that has silently
 *      rotted is discovered at exactly the wrong moment.
 */

import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import fs from "node:fs";
import path from "node:path";

import TournamentBracket from "@/components/tournament/TournamentBracket";
import PlayoffGrid from "@/components/tournament/PlayoffGrid";
import { readPlayoffGrid, type PlayoffGrid as GridModel } from "@/lib/playoffGrid";
import type { TournamentPayload } from "@/lib/tournament";

const MOCKS = path.join(__dirname, "..", "..", "..", "docs", "mocks", "us-open");

/** The app's real compiled Tailwind, so the capture is not a lookalike. */
function appStylesheet(): string {
  const dir = path.join(__dirname, "..", "..", ".next", "static", "css");
  try {
    return fs
      .readdirSync(dir)
      .filter((f) => f.endsWith(".css"))
      .map((f) => fs.readFileSync(path.join(dir, f), "utf8"))
      .join("\n");
  } catch {
    return "";
  }
}

/**
 * THE ROUTE'S OWN OUTPUT, committed.
 *
 * Generated by running `build_boards` / `build_grids` / `build_slate` /
 * `build_props` / `build_results` over register v7 and a bounded
 * `/api/admin/db-query` price read for the 514 outcomes the register pins. The
 * only thing not production about it is that it is a file.
 */
const PAYLOAD = JSON.parse(
  fs.readFileSync(path.join(MOCKS, "payload-2026-08-27.json"), "utf8")
) as TournamentPayload;

const MEN = PAYLOAD.boards[0];
const WOMEN = PAYLOAD.boards[1];

function gridFor(draw: string): GridModel {
  const grid = readPlayoffGrid(PAYLOAD.grids?.[draw]);
  if (grid === null) throw new Error(`payload carries no grid for ${draw}`);
  return grid;
}

const MENS_GRID = gridFor("mens-singles");
const WOMENS_GRID = gridFor("womens-singles");

/**
 * How many rows have no ladder at ALL — every reach cell censused absent.
 *
 * DERIVED, never typed into the prose. The previous artifact's caption said
 * "Sinner leads the board", which was true of the 2026-08-25 payload and false
 * by the time the outright fields came back live — a hand-written number in a
 * caption is a claim with no test behind it, sitting next to rendered data that
 * disagrees with it. Anything countable in these notes is computed here.
 */
function noLadderRows(grid: GridModel): number {
  const reach = grid.columns.filter((column) => column.kind === "reach");
  return grid.rows.filter((row) =>
    reach.every((column) => row.cells[column.key]?.state === "no_market")
  ).length;
}

const MENS_NO_LADDER = noLadderRows(MENS_GRID);
const WOMENS_NO_LADDER = noLadderRows(WOMENS_GRID);

/** Rows the ladder prices that carry no outright quote — the unranked tail. */
function ladderOnly(grid: GridModel): string[] {
  return grid.rows.filter((row) => !row.onBoard).map((row) => row.displayName);
}

describe("the committed payload is the route's real output", () => {
  it("carries a grid for both draws", () => {
    expect(Object.keys(PAYLOAD.grids ?? {}).sort()).toEqual([
      "mens-singles",
      "womens-singles",
    ]);
  });

  it("includes the SEMIFINAL column — ruling 4's named defect", () => {
    // "The second-week grid must include the SEMIFINAL column (it jumped
    // QF->title)." It jumped because UX-P138 capped the grid at three reach
    // columns. There is no cap; if one ever returns, this fails.
    for (const grid of [MENS_GRID, WOMENS_GRID]) {
      expect(grid.columns.map((c) => c.key)).toEqual(["R16", "QF", "SF", "F", "title"]);
    }
  });

  it("has ZERO alarm cells — the ship condition", () => {
    // Alex's amendment: an unlinked cell is a linkage defect with a named fix,
    // not a data quirk. Non-zero here means the artifact should not ship.
    expect(MENS_GRID.alarmCells).toBe(0);
    expect(WOMENS_GRID.alarmCells).toBe(0);
  });

  it("accounts for every cell it renders", () => {
    for (const grid of [MENS_GRID, WOMENS_GRID]) {
      const counted = Object.values(grid.counts).reduce((a, b) => a + b, 0);
      expect(counted).toBe(grid.totalCells);
      expect(grid.totalCells).toBe(grid.rows.length * grid.columns.length);
    }
  });
});

describe("the bracket capture rig still renders every state", () => {
  it("renders the pre-draw notice WITH the ceremony date — Alex's item 1", () => {
    const html = renderToStaticMarkup(
      <TournamentBracket
        grid={null}
        drawReleased={false}
        preDrawBoards={PAYLOAD.boards}
        drawReleaseLabel={PAYLOAD.draw_release_label}
        mainDrawLabel={PAYLOAD.main_draw_label}
      />
    );
    expect(html).toContain('data-testid="bracket-unreleased"');
    expect(html).toContain('data-has-release-time="true"');
    expect(html).toContain("Thursday 27 August, 12:00 ET");
    expect(html).toContain("Sunday 30 August");
    expect((html.match(/data-testid="tournament-board"/g) ?? []).length).toBe(2);
  });

  it("shows the grid BEFORE the draw, because its markets are live now", () => {
    const html = renderToStaticMarkup(
      <TournamentBracket
        grid={MENS_GRID}
        drawReleased={false}
        drawReleaseLabel={PAYLOAD.draw_release_label}
        mainDrawLabel={PAYLOAD.main_draw_label}
      />
    );
    expect(html).toContain('data-testid="playoff-grid"');
    // And still says when the draw is, so the two facts sit together.
    expect(html).toContain("Thursday 27 August, 12:00 ET");
  });

  it("prints NO BLANK CELL anywhere — Alex's dealbreaker", () => {
    for (const grid of [MENS_GRID, WOMENS_GRID]) {
      const html = renderToStaticMarkup(
        <PlayoffGrid grid={grid} drawLabel={grid.label} initialExpanded />
      );
      const cells = html.match(/data-testid="grid-cell"/g) ?? [];
      expect(cells.length).toBe(grid.totalCells);
      // Every cell carries a state, and no state is empty.
      const states = [...html.matchAll(/data-testid="grid-cell"[^>]*data-state="([^"]*)"/g)].map(
        (m) => m[1]
      );
      expect(states.length).toBe(grid.totalCells);
      expect(states.every((s) => s.length > 0)).toBe(true);
    }
  });

  it("shows the sum check, with the Final column's failure visible", () => {
    const html = renderToStaticMarkup(<PlayoffGrid grid={MENS_GRID} initialExpanded />);
    expect(html).toContain('data-testid="grid-sum-check"');
    expect(html).toContain('data-testid="grid-sum-row"');
    // Measured 2026-08-26: the men's Final column sums to 2.78 against 2
    // places. Reported as `over`, never rescaled.
    const finalCheck = MENS_GRID.columnSums.find((c) => c.key === "F");
    expect(finalCheck?.verdict).toBe("over");
    expect(html).toContain('data-verdict="over"');
    // And QF/SF pass, so the check is discriminating rather than always red.
    expect(MENS_GRID.columnSums.find((c) => c.key === "QF")?.verdict).toBe("pass");
    expect(MENS_GRID.columnSums.find((c) => c.key === "SF")?.verdict).toBe("pass");
  });

  it("the women's grid is a genuinely different field, not the men's twice", () => {
    const men = renderToStaticMarkup(<PlayoffGrid grid={MENS_GRID} initialExpanded />);
    const women = renderToStaticMarkup(<PlayoffGrid grid={WOMENS_GRID} initialExpanded />);
    expect(men).toContain("Alcaraz");
    expect(women).toContain("Sabalenka");
    expect(women).not.toContain("Alcaraz");
  });

  it("the five-column men's grid SCROLLS, so no column is clipped away (ruling 5, #3072)", () => {
    // This assertion used to read `data-scrolls="false"`, on the arithmetic
    // `118 + 5×46 = 348` inside a "358px" box. Both numbers were wrong: a row
    // also carries `px-3.5` and `gap-1.5` (so 406px), and the card's measured
    // client box on a 390px phone is 332px. Production showed the consequence —
    // the Title column drawn outside an `overflow-x: hidden` card, unreachable.
    // Ruling 5 says a column is never dropped; clipping one IS dropping it.
    const html = renderToStaticMarkup(<PlayoffGrid grid={MENS_GRID} />);
    expect(html).toContain('data-scrolls="true"');
    expect(html).toContain("overflow-x-auto");
    expect(html).toContain('data-kind="title"');
  });

  it("writes the capture when UX_CAPTURE_DIR is set", () => {
    const dir = process.env.UX_CAPTURE_DIR;
    if (!dir) {
      expect(true).toBe(true);
      return;
    }
    fs.mkdirSync(dir, { recursive: true });

    const phone = (
      caption: string,
      note: string,
      body: React.ReactElement,
      women = false,
      showPills = true
    ) => `
  <div class="col">
    <div class="cap">${caption}</div>
    <div class="phone">
      <header class="hero"><h1>US Open 2026</h1><p>Flushing Meadows &middot; 08-30 to 09-13</p></header>
      <div class="tabs"><span>Tournament</span><span class="on">Bracket</span></div>
      ${
        showPills
          ? `<div class="pills"><span${women ? "" : ' class="on"'}>Men's</span><span${
              women ? ' class="on"' : ""
            }>Women's</span></div>`
          : ""
      }
      <div class="pad">${renderToStaticMarkup(body)}</div>
    </div>
    <div class="sub">${note}</div>
  </div>`;

    // Hoisted out of the caption template: a call expression nested three
    // backticks deep parses badly, and a caption is not worth a type error.
    const womensLadderOnly = ladderOnly(WOMENS_GRID);
    const womensLadderOnlyNames = womensLadderOnly.slice(0, 3).join(", ");
    const mensPriced = MENS_GRID.pricedCells;
    const mensTotal = MENS_GRID.totalCells;
    const womensPriced = WOMENS_GRID.pricedCells;
    const womensTotal = WOMENS_GRID.totalCells;

    const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>US Open — the bracket grid with zero gaps (UX-P139)</title>
<style>${appStylesheet()}</style>
<style>
  body{background:#F5F5F7;margin:0;font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text",Segoe UI,Roboto,sans-serif}
  .note{max-width:1300px;margin:0 auto;padding:16px;font-size:12.5px;line-height:1.6;color:#374151;background:#fff;border-bottom:1px solid #E5E7EB}
  .note b{color:#111827}
  .note ol{margin:8px 0 0;padding-left:20px}
  .note li{margin-bottom:5px}
  .warn{background:#FFFBEB;border:1px solid #FDE68A;border-radius:10px;padding:11px 14px;margin:10px 0 0}
  .good{background:#F0FDF4;border:1px solid #BBF7D0;border-radius:10px;padding:11px 14px;margin:10px 0 0}
  .rail{display:flex;gap:22px;justify-content:center;align-items:flex-start;flex-wrap:wrap;padding:20px 16px 60px;max-width:1400px;margin:0 auto}
  .col{width:390px}
  .phone{width:390px;background:#F5F5F7;border:1px solid #E5E7EB;border-radius:12px;overflow:hidden;max-height:900px;overflow-y:auto}
  .cap{font:700 11.5px inherit;letter-spacing:.07em;text-transform:uppercase;color:#6B7280;padding:0 2px 7px}
  .sub{padding:9px 2px 0;font-size:11.5px;line-height:1.5;color:#6B7280}
  .sub b{color:#111827}
  .tabs{display:flex;border-bottom:1px solid #E5E7EB;background:#fff}
  .tabs span{flex:1;text-align:center;padding:13px 0;font:600 13.5px inherit;color:#9CA3AF;border-bottom:2px solid transparent}
  .tabs span.on{color:#111827;border-bottom-color:#111827}
  .pills{display:flex;gap:6px;padding:0 16px 12px;background:#fff;border-bottom:1px solid #E5E7EB}
  .pills span{border-radius:999px;padding:6px 14px;font:600 13px inherit;background:#F0F0F2;color:#6B7280}
  .pills span.on{background:#111827;color:#F8FAFC}
  header.hero{padding:16px;background:#fff;border-bottom:1px solid #E5E7EB}
  header.hero h1{margin:0;font-size:24px;letter-spacing:-.02em;color:#111827}
  header.hero p{margin:2px 0 0;font-size:13px;color:#6B7280}
  .pad{padding:16px}
  .lead{background:#111827;color:#F8FAFC;padding:10px 16px;font:700 12px inherit;letter-spacing:.06em;text-transform:uppercase}
  table.census{border-collapse:collapse;margin:10px 0 0;font-size:12px}
  table.census th,table.census td{border:1px solid #E5E7EB;padding:4px 9px;text-align:left}
  table.census th{background:#F9FAFB;font-weight:700;color:#111827}
</style></head>
<body>
<div class="note">
<b>THE GRID HAS NO GAPS. Every cell here is a market's answer to exactly its own column, or a
written-down census result saying no such market exists.</b> These are the SHIPPED components, the
app's own compiled CSS, and the route's real output over register v7 at a 390px viewport.

<div class="good">
<b>YOUR AMENDMENT, ANSWERED.</b> The register now carries a per-player per-round cell with market
IDs from both sources &mdash; 448 cells, 336 of them pinned to a live Polymarket market. The grid
reads that and nothing else: there is no code path by which a match price, a chained product or a
curated prop can reach a cell. Wrong-future placement is a <b>validation failure</b>
(<code>REACH_ROUND_MISMATCH</code>), so a reach-QF market wired into the SF cell means the register
does not load at all rather than rendering a plausible number. <b>Alarm cells: 0.</b>
<br><br>
<b>The interleaved hole you named is gone outright.</b> Every one of the 84 players with a ladder
has all four rounds &mdash; there is no longer any player anywhere with a quarter-final number, a
title number and a blank between them, and a backend test asserts that as a property of the
committed file rather than as an observation.
</div>

<div class="warn">
<b>WHERE YOUR AXIOM DOES NOT HOLD, measured against both sources' own inventories.</b> You wrote
that Kalshi AND Polymarket carry a future for every player and every round. They do not, and this
is the one place I have to disagree with the premise rather than the ruling:
<table class="census">
<tr><th>Source</th><th>Round-advancement futures for this tournament</th></tr>
<tr><td>Kalshi</td><td><b>Zero.</b> Its entire US Open inventory is 5 markets: the two outright
winner fields, two &ldquo;will X play&rdquo;, and a ticket-price market.</td></tr>
<tr><td>Polymarket</td><td><b>336</b>, in 8 events &mdash; To&nbsp;Reach {R16, QF, SF, Final} &times;
{Men's, Women's}. 44 of 128 men, 40 of 128 women. Verified against Gamma directly, so this is their
inventory and not a shortfall in our ingest.</td></tr>
</table>
So ${MENS_NO_LADDER + WOMENS_NO_LADDER} board contenders have no reach market anywhere
(${MENS_NO_LADDER} men, ${WOMENS_NO_LADDER} women) &mdash; Jannik Sinner among them. Those cells say
<b>NO MKT</b> and carry the date we last looked. That is a census
result, not a gap: it is materially different from a broken link, it is counted separately, and it
is not an alarm. The alarm states (<code>!</code>) are reserved for cells that are our fault, and
there are none.
</div>

<ol>
<li><b>The semifinal column is here</b> (ruling 4). It was missing because UX-P138 capped the grid
at three reach columns and SF was the fourth. There is no cap now; a column is never dropped.</li>
<li><b>The sum check is under every grid</b> (ruling 4), per column, with its ratio. QF and SF pass;
<b>the Final column sums to 2.78 against 2 places</b> and says so. Nothing is rescaled to make it
add up &mdash; a normalised column is a column of fabricated numbers.</li>
<li><b>Wide rounds scroll</b> (ruling 5), and at five columns this one does: a row is 28px of side
padding plus 118px for the name plus 5&times;46px of columns plus 5&times;6px of gaps &mdash; 406px
inside the card's measured 332px box. It used to be declared a fit at &ldquo;348 inside 358&rdquo;,
which counted neither the gaps nor the padding, and the Title column was clipped away instead
(#3072).</li>
<li><b>The draw panel says WHEN</b> (item 1): <b>Thursday 27 August, 12:00 ET</b>, first round
Sunday 30 August. And the grid no longer waits for it &mdash; its markets are live today.</li>
<li><b>Coverage:</b> men's <b>${mensPriced} of ${mensTotal}</b> cells priced, women's
<b>${womensPriced} of ${womensTotal}</b>. The rest are the censused absences above.</li>
</ol>

<div class="warn">
<b>ON THE 15-DAY-OLD DATA THAT SPOOKED YOU &mdash; it was REAL, and it is now fixed.</b> Not a mock
artifact, and the evidence is exact: in the UX-P138 capture, 19 men's rows &mdash; Alcaraz,
Djokovic, Zverev, Sinner among them &mdash; carried an age of <b>362.5 hours, which is 15.1 days</b>.
That was a genuine production read of genuinely dark markets. The proof it was not the FILE being
old is that the register pins the <b>same 118 outright outcome IDs today, all 118 unchanged</b>, and
those same IDs now read <b>2.4 hours old at Kalshi and 4.5 at Polymarket</b>. Every title number in
this artifact is therefore <b>live</b>, captured minutes before it was rendered. What is still
behind is the reach ladder: <b>28&ndash;32 hours</b>, which is why the middle columns render muted
as <code>stale</code> and say their age. The cause is structural: Gamma caps offset
pagination at 2,000, so the scanning poll rotates a window and reaches a given event roughly once a
day. The fix ships with this queue &mdash; a 10-minute task that asks Gamma for exactly the market
IDs the register pins, a read that does not paginate and so is not capped. <b>The guarantee is not
that data is never old; it is that old data can never look current.</b> Every muted number below is
muted because it is stale, and it says its age. Nothing on this page can print a stale number in
the confident type.
</div>
</div>

<div class="lead">1 &mdash; Before the draw: the date, and a grid that is already priced</div>
<div class="rail">
${phone(
  "1 &middot; Men's &mdash; the pre-draw tab as it ships",
  "The ceremony's date and time lead the panel (item 1). Below it, the real grid &mdash; because the round-advancement markets are live now and withholding a priced grid until a ceremony would be an empty page over tradeable truth.",
  <TournamentBracket
    grid={MENS_GRID}
    drawReleased={false}
    drawLabel={MEN.label}
    drawReleaseLabel={PAYLOAD.draw_release_label}
    mainDrawLabel={PAYLOAD.main_draw_label}
  />
)}
${phone(
  "2 &middot; The boards-only fallback",
  "What renders if the grid ever comes back empty &mdash; both winner boards, unfiltered by the pill. UX-P137 ruling 1, kept as the floor.",
  <TournamentBracket
    grid={null}
    drawReleased={false}
    preDrawBoards={PAYLOAD.boards}
    drawReleaseLabel={PAYLOAD.draw_release_label}
    mainDrawLabel={PAYLOAD.main_draw_label}
  />,
  false,
  false
)}
</div>

<div class="lead">2 &mdash; The grid itself, both draws, real data</div>
<div class="rail">
${phone(
  "3 &middot; Men's &mdash; collapsed",
  `Five columns: R16, QF, SF, Final, Title. Sabalenka's row on the women's side and Alcaraz's here are complete left to right &mdash; the ladder shape the market actually prices. ${mensPriced} of ${mensTotal} cells carry a price.`,
  <PlayoffGrid grid={MENS_GRID} drawLabel={MEN.label} />
)}
${phone(
  "4 &middot; Women's &mdash; collapsed",
  `A genuinely different field, same component. ${womensPriced} of ${womensTotal} cells priced. Sabalenka 84 &rarr; 78 &rarr; 51 &rarr; 36 &rarr; 26 reads down the row without a single hole in it.`,
  <PlayoffGrid grid={WOMENS_GRID} drawLabel={WOMEN.label} />,
  true
)}
</div>

<div class="lead">3 &mdash; Expanded: every row, including the ones with no market</div>
<div class="rail">
${phone(
  "5 &middot; Men's &mdash; all 56 rows",
  `Alcaraz leads at ${(MENS_GRID.rows[0].cells.title.probability! * 100).toFixed(1)}% and reads clean across all five columns. The row worth looking at hardest is <b>Jannik Sinner</b>: no reach market at either source, so his four middle cells say NO MKT beside a live title price of 0.6% &mdash; the market pricing his withdrawal, not his form. ${MENS_NO_LADDER} men's rows have no ladder anywhere.`,
  <PlayoffGrid grid={MENS_GRID} drawLabel={MEN.label} initialExpanded />
)}
${phone(
  "6 &middot; Women's &mdash; all 56 rows",
  `The last ${womensLadderOnly.length} rows are players the ladder prices who have no outright quote &mdash; ${womensLadderOnlyNames}. They sort after the ranked field and their title cell says NO MKT.`,
  <PlayoffGrid grid={WOMENS_GRID} drawLabel={WOMEN.label} initialExpanded />,
  true
)}
</div>
</body></html>`;

    const out = path.join(dir, "us-open-bracket.html");
    fs.writeFileSync(out, html);
    expect(fs.statSync(out).size).toBeGreaterThan(20000);
  });
});
