/**
 * Static data for the Oscars landing page.
 * Ceremony order, category metadata, and emoji mapping.
 */

/** Category keys in ceremony presentation order (98th Academy Awards, March 2, 2026) */
export const CEREMONY_ORDER: string[] = [
  "best_supporting_actor",
  "best_casting",
  "best_animated_short",
  "best_live_action_short",
  "best_makeup_hairstyling",
  "best_costume_design",
  "best_documentary_short",
  "best_sound",
  "best_original_score",
  "best_film_editing",
  "best_visual_effects",
  "best_animated_feature",
  "best_supporting_actress",
  "best_original_song",
  "best_international_feature",
  "best_documentary_feature",
  "best_adapted_screenplay",
  "best_production_design",
  "best_cinematography",
  "best_original_screenplay",
  "best_director",
  "best_actress",
  "best_actor",
  "best_picture",
];

/** Major (acting/directing/picture) categories get larger cards */
export const MAJOR_CATEGORIES = new Set([
  "best_picture",
  "best_director",
  "best_actor",
  "best_actress",
  "best_supporting_actor",
  "best_supporting_actress",
]);

/** Person categories — search TMDB for people, not movies */
export const PERSON_CATEGORIES = new Set([
  "best_actor",
  "best_actress",
  "best_supporting_actor",
  "best_supporting_actress",
  "best_director",
]);

/** Emoji for each category */
export const CATEGORY_EMOJI: Record<string, string> = {
  best_picture: "\uD83C\uDFAC",
  best_director: "\uD83C\uDFAC",
  best_actor: "\uD83C\uDFAD",
  best_actress: "\uD83C\uDFAD",
  best_supporting_actor: "\uD83C\uDFAD",
  best_supporting_actress: "\uD83C\uDFAD",
  best_original_screenplay: "\u270D\uFE0F",
  best_adapted_screenplay: "\u270D\uFE0F",
  best_animated_feature: "\uD83E\uDDF8",
  best_international_feature: "\uD83C\uDF0D",
  best_documentary_feature: "\uD83D\uDCF9",
  best_documentary_short: "\uD83D\uDCF9",
  best_animated_short: "\uD83E\uDDF8",
  best_live_action_short: "\uD83C\uDFAC",
  best_original_score: "\uD83C\uDFB5",
  best_original_song: "\uD83C\uDFA4",
  best_sound: "\uD83D\uDD0A",
  best_production_design: "\uD83C\uDFD7\uFE0F",
  best_cinematography: "\uD83D\uDCF7",
  best_film_editing: "\u2702\uFE0F",
  best_costume_design: "\uD83E\uDDE5",
  best_makeup_hairstyling: "\uD83D\uDC84",
  best_visual_effects: "\u2728",
  best_casting: "\uD83C\uDFAD",
};

/**
 * Hardcoded 98th Academy Awards nominees (March 15, 2026).
 * Used as fallback when prediction market data is unavailable (markets closed post-ceremony).
 * Probabilities are approximate pre-ceremony consensus odds.
 */
export const NOMINEES_98TH: Record<string, { name: string; probability: number }[]> = {
  best_picture: [
    { name: "Sinners", probability: 0.28 },
    { name: "One Battle After Another", probability: 0.22 },
    { name: "Sentimental Value", probability: 0.15 },
    { name: "Frankenstein", probability: 0.10 },
    { name: "Hamnet", probability: 0.08 },
    { name: "Marty Supreme", probability: 0.06 },
    { name: "F1", probability: 0.04 },
    { name: "Bugonia", probability: 0.03 },
    { name: "The Secret Agent", probability: 0.02 },
    { name: "Train Dreams", probability: 0.02 },
  ],
  best_director: [
    { name: "Paul Thomas Anderson", probability: 0.35 },
    { name: "Ryan Coogler", probability: 0.25 },
    { name: "Chloe Zhao", probability: 0.18 },
    { name: "Josh Safdie", probability: 0.12 },
    { name: "Joachim Trier", probability: 0.10 },
  ],
  best_actor: [
    { name: "Timothee Chalamet", probability: 0.35 },
    { name: "Michael B. Jordan", probability: 0.30 },
    { name: "Leonardo DiCaprio", probability: 0.15 },
    { name: "Paul Mescal", probability: 0.12 },
    { name: "Ethan Hawke", probability: 0.08 },
  ],
  best_actress: [
    { name: "Jessie Buckley", probability: 0.50 },
    { name: "Emma Stone", probability: 0.18 },
    { name: "Renate Reinsve", probability: 0.14 },
    { name: "Demi Moore", probability: 0.10 },
    { name: "Saoirse Ronan", probability: 0.08 },
  ],
  best_supporting_actor: [
    { name: "Stellan Skarsgard", probability: 0.25 },
    { name: "Sean Penn", probability: 0.22 },
    { name: "Delroy Lindo", probability: 0.20 },
    { name: "Jacob Elordi", probability: 0.18 },
    { name: "Benicio Del Toro", probability: 0.15 },
  ],
  best_supporting_actress: [
    { name: "Amy Madigan", probability: 0.30 },
    { name: "Wunmi Mosaku", probability: 0.22 },
    { name: "Elle Fanning", probability: 0.20 },
    { name: "Teyana Taylor", probability: 0.15 },
    { name: "Inga Ibsdotter Lilleaas", probability: 0.13 },
  ],
  best_original_screenplay: [
    { name: "Sinners", probability: 0.30 },
    { name: "Marty Supreme", probability: 0.25 },
    { name: "Sentimental Value", probability: 0.20 },
    { name: "It Was Just an Accident", probability: 0.15 },
    { name: "Blue Moon", probability: 0.10 },
  ],
  best_adapted_screenplay: [
    { name: "One Battle After Another", probability: 0.30 },
    { name: "Frankenstein", probability: 0.25 },
    { name: "Hamnet", probability: 0.20 },
    { name: "Train Dreams", probability: 0.15 },
    { name: "Bugonia", probability: 0.10 },
  ],
  best_animated_feature: [
    { name: "KPop Demon Hunters", probability: 0.35 },
    { name: "Elio", probability: 0.22 },
    { name: "Zootopia 2", probability: 0.18 },
    { name: "Arco", probability: 0.15 },
    { name: "Little Amelie or the Character of Rain", probability: 0.10 },
  ],
  best_international_feature: [
    { name: "The Secret Agent", probability: 0.30 },
    { name: "Sentimental Value", probability: 0.25 },
    { name: "It Was Just an Accident", probability: 0.20 },
    { name: "Sirat", probability: 0.15 },
    { name: "The Voice of Hind Rajab", probability: 0.10 },
  ],
  best_documentary_feature: [
    { name: "The Alabama Solution", probability: 0.30 },
    { name: "Come See Me in the Good Light", probability: 0.25 },
    { name: "Cutting Through Rocks", probability: 0.20 },
    { name: "Mr. Nobody Against Putin", probability: 0.15 },
    { name: "The Perfect Neighbor", probability: 0.10 },
  ],
  best_documentary_short: [
    { name: "All the Empty Rooms", probability: 0.25 },
    { name: "Armed Only with a Camera", probability: 0.22 },
    { name: "Children No More", probability: 0.20 },
    { name: "The Devil Is Busy", probability: 0.18 },
    { name: "Perfectly a Strangeness", probability: 0.15 },
  ],
  best_animated_short: [
    { name: "Butterfly", probability: 0.25 },
    { name: "Forevergreen", probability: 0.22 },
    { name: "The Girl Who Cried Pearls", probability: 0.20 },
    { name: "Retirement Plan", probability: 0.18 },
    { name: "The Three Sisters", probability: 0.15 },
  ],
  best_live_action_short: [
    { name: "The Singers", probability: 0.25 },
    { name: "Two People Exchanging Saliva", probability: 0.22 },
    { name: "Butcher's Stain", probability: 0.20 },
    { name: "Jane Austen's Period Drama", probability: 0.18 },
    { name: "A Friend of Dorothy", probability: 0.15 },
  ],
  best_original_score: [
    { name: "Sinners", probability: 0.30 },
    { name: "Frankenstein", probability: 0.25 },
    { name: "Hamnet", probability: 0.18 },
    { name: "One Battle After Another", probability: 0.15 },
    { name: "Bugonia", probability: 0.12 },
  ],
  best_original_song: [
    { name: "Golden - KPop Demon Hunters", probability: 0.35 },
    { name: "I Lied to You - Sinners", probability: 0.25 },
    { name: "Train Dreams - Train Dreams", probability: 0.18 },
    { name: "Dear Me - Diane Warren: Relentless", probability: 0.12 },
    { name: "Sweet Dreams of Joy - Viva Verdi!", probability: 0.10 },
  ],
  best_sound: [
    { name: "Sinners", probability: 0.28 },
    { name: "Frankenstein", probability: 0.25 },
    { name: "One Battle After Another", probability: 0.20 },
    { name: "F1", probability: 0.15 },
    { name: "Marty Supreme", probability: 0.12 },
  ],
  best_production_design: [
    { name: "Frankenstein", probability: 0.30 },
    { name: "One Battle After Another", probability: 0.25 },
    { name: "Hamnet", probability: 0.20 },
    { name: "Marty Supreme", probability: 0.15 },
    { name: "Sinners", probability: 0.10 },
  ],
  best_cinematography: [
    { name: "Sinners", probability: 0.28 },
    { name: "One Battle After Another", probability: 0.25 },
    { name: "Frankenstein", probability: 0.20 },
    { name: "Marty Supreme", probability: 0.15 },
    { name: "Train Dreams", probability: 0.12 },
  ],
  best_film_editing: [
    { name: "Sinners", probability: 0.28 },
    { name: "One Battle After Another", probability: 0.25 },
    { name: "Marty Supreme", probability: 0.20 },
    { name: "Sentimental Value", probability: 0.15 },
    { name: "Frankenstein", probability: 0.12 },
  ],
  best_costume_design: [
    { name: "Frankenstein", probability: 0.30 },
    { name: "Hamnet", probability: 0.25 },
    { name: "One Battle After Another", probability: 0.18 },
    { name: "Marty Supreme", probability: 0.15 },
    { name: "Sinners", probability: 0.12 },
  ],
  best_makeup_hairstyling: [
    { name: "Frankenstein", probability: 0.35 },
    { name: "Sinners", probability: 0.22 },
    { name: "Kokuho", probability: 0.18 },
    { name: "The Smashing Machine", probability: 0.13 },
    { name: "The Ugly Stepsister", probability: 0.12 },
  ],
  best_visual_effects: [
    { name: "Avatar: Fire and Ash", probability: 0.30 },
    { name: "Sinners", probability: 0.22 },
    { name: "F1", probability: 0.20 },
    { name: "Jurassic World Rebirth", probability: 0.15 },
    { name: "The Lost Bus", probability: 0.13 },
  ],
  best_casting: [
    { name: "One Battle After Another", probability: 0.28 },
    { name: "Sinners", probability: 0.25 },
    { name: "Hamnet", probability: 0.20 },
    { name: "Marty Supreme", probability: 0.15 },
    { name: "The Secret Agent", probability: 0.12 },
  ],
};

/** Official category descriptions (for tooltips) */
export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  best_picture: "Best Motion Picture of the Year",
  best_director: "Best Achievement in Directing",
  best_actor: "Best Actor in a Leading Role",
  best_actress: "Best Actress in a Leading Role",
  best_supporting_actor: "Best Actor in a Supporting Role",
  best_supporting_actress: "Best Actress in a Supporting Role",
  best_original_screenplay: "Best Original Screenplay",
  best_adapted_screenplay: "Best Adapted Screenplay",
  best_animated_feature: "Best Animated Feature Film",
  best_international_feature: "Best International Feature Film",
  best_documentary_feature: "Best Documentary Feature",
  best_documentary_short: "Best Documentary Short Film",
  best_animated_short: "Best Animated Short Film",
  best_live_action_short: "Best Live Action Short Film",
  best_original_score: "Best Original Score",
  best_original_song: "Best Original Song",
  best_sound: "Best Achievement in Sound",
  best_production_design: "Best Production Design",
  best_cinematography: "Best Cinematography",
  best_film_editing: "Best Film Editing",
  best_costume_design: "Best Costume Design",
  best_makeup_hairstyling: "Best Makeup and Hairstyling",
  best_visual_effects: "Best Visual Effects",
  best_casting: "Best Casting",
};
