// A coverage census produced by THE SERVE PATH, not typed out here.
//
// Generated by calling `attach_coverage_census`
// (`backend/app/utils/calibration_coverage_consumer.py`) on a payload shaped
// like the one production serves today — an explicitly-unavailable census
// stamped with the build's generation — with a reconciling published walk and
// a matching cursor, and pasting the attached block verbatim. That is the whole
// composition this page's render depends on, in the one direction nothing else
// tests: producer → consumer → wire → selector.
//
// Two things nobody would have guessed, and both would have shipped a
// component that renders for nobody:
//
//   * `status` is "incomplete", permanently. The serve-time attach cannot
//     supply `sportsbook_curve_legs`, so the observation bridge reports UNKNOWN
//     and the overall status can never be "complete". A selector gated on
//     `status === "complete"` would be dead code.
//   * the coverage bridge reconciles ANYWAY, because it is a different unit
//     with its own reconciliation. That is the number a reader gets.
//
// ONE RUNG IS NOT FROM THAT CAPTURE, and it is called out rather than blended
// in: `identity_disputed` (#6275) is appended at `outcomes: 0`, carrying the
// server's verbatim `rule` text. The quarantine had not run in production when
// the block above was captured, so the serve path could not yet emit it. Zero
// is the honest count — it leaves every reconciliation in this fixture
// arithmetically untouched (it lands in `emptyRules`, not in `rows`) instead of
// inventing a bucket and hand-balancing the other numbers to match. When a
// production census that includes the quarantine can be captured, re-capture
// the whole block verbatim and delete this paragraph.
export const COMPLETE_CENSUS = {
  "schema_version": "calibration-coverage-bridge/v1",
  "status": "incomplete",
  "population_version": "q271",
  "generation": "1789409700464",
  "units": {
    "published_curve_observations": {
      "unit": "curve_observation",
      "value": 737431,
      "rule": "One row plotted on the published calibration curve. Futures outcomes are one contributing population; the sportsbook curves (moneyline, spreads, totals, per-sportsbook moneyline) contribute observations that are not futures outcomes."
    },
    "outcomes_with_calibration_coverage": {
      "unit": "futures_outcome",
      "value": 734400,
      "rule": "One resolved futures outcome carrying a usable calibration price (opening probability strictly between 0 and 1, terminal calibration price preferred). This is the population calibration COVERS; it is not the population the curve PLOTS.",
      "with_terminal_calibration_price": 301002
    }
  },
  "coverage_bridge": {
    "from": "outcomes_with_calibration_coverage",
    "to": "plotted_on_curve",
    "unit": "futures_outcome",
    "rungs": [
      {
        "key": "plotted_on_curve",
        "unit": "futures_outcome",
        "outcomes": 412889,
        "checked": true,
        "rule": "Plotted on the published curve \u2014 survived every eligibility, truth, liquidity, shape and representative rule."
      },
      {
        "key": "market_result_unavailable",
        "unit": "futures_outcome",
        "outcomes": 1204,
        "checked": true,
        "rule": "The whole market is withheld symmetrically because its result cannot be established (DataGolf recovery residual): winners AND losers are dropped together so participation is never one-sidedly assumed."
      },
      {
        "key": "truth_source_missing",
        "unit": "futures_outcome",
        "outcomes": 58311,
        "checked": true,
        "rule": "The outcome carries no resolution source at all, so nothing independent grades it."
      },
      {
        "key": "truth_ineligible_source",
        "unit": "futures_outcome",
        "outcomes": 9442,
        "checked": true,
        "rule": "The outcome's winner was established by a source that is not independent of the market's own price (price-derived or guess-family), so it cannot grade its own forecast."
      },
      {
        "key": "identity_disputed",
        "unit": "futures_outcome",
        "outcomes": 0,
        "checked": true,
        "rule": "The market's own ID names a different game day than the game it is attached to, so the result it would be graded against belongs to some other game. Held out of the published curves as under review until the identity is verified."
      },
      {
        "key": "question_ungraded",
        "unit": "futures_outcome",
        "outcomes": 22170,
        "checked": true,
        "rule": "The virtual question this outcome belongs to graded no winner at all, so its members are unknown truth rather than confident losses."
      },
      {
        "key": "malformed_or_unknown_truth",
        "unit": "futures_outcome",
        "outcomes": 3915,
        "checked": true,
        "rule": "The market's captured result is not a scoreable prediction: nobody graded a winner, a two-outcome partition graded zero or two, a draw-capable duel captured no draw member, or a declared field captured one member or fewer."
      },
      {
        "key": "phantom_liquidity",
        "unit": "futures_outcome",
        "outcomes": 71608,
        "checked": true,
        "rule": "The price is a phantom, not a forecast: a Kalshi outcome that was never bid and never traded, or a Polymarket no-bid placeholder sitting in the near-0.50 band."
      },
      {
        "key": "opening_below_writer_bar",
        "unit": "futures_outcome",
        "outcomes": 18233,
        "checked": true,
        "rule": "The opening price is one our own Kalshi writer would have refused to record: no snapshot of this outcome ever showed a real bid with a bid-ask spread under 0.50, so the price was never discovered."
      },
      {
        "key": "structural_artifact",
        "unit": "futures_outcome",
        "outcomes": 6077,
        "checked": true,
        "rule": "A measured pricing artifact rather than a genuine probability: esports match bundles, golf one-sided-ask placeholders, Kalshi player-prop threshold captures in the settlement-collapse band, and wide-spread weather midpoints."
      },
      {
        "key": "field_incomplete",
        "unit": "futures_outcome",
        "outcomes": 0,
        "checked": true,
        "rule": "The outcome belongs to a normalization field that lost a member to an exclusion above, so the partition no longer sums to one and is dropped whole rather than normalized over its survivors."
      },
      {
        "key": "representative_not_selected",
        "unit": "futures_outcome",
        "outcomes": 130551,
        "checked": true,
        "rule": "The question is published, but this outcome is not the row that represents it: a non-representative binary side, a placeholder modal price, or an extreme tail in a non-partition multi pool."
      }
    ],
    "reconciles": true,
    "residual": 0
  },
  "reachability_bridge": {
    "status": "unavailable",
    "reason": "the reachability tier is the builder's rail and is not re-read at serve time; this census reconciles the coverage bridge only",
    "unit": "futures_outcome",
    "from": "resolved_futures_outcomes",
    "to": "outcomes_with_calibration_coverage",
    "tiers": [
      {
        "key": "priced_in_coverage",
        "unit": "futures_outcome",
        "outcomes": null,
        "checked": false,
        "rule": "Carries a usable calibration price, so it enters the coverage bridge and is accounted for there. This tier is the hinge between the two reconciliations, not a second headline."
      },
      {
        "key": "unpriced_provably_purged",
        "unit": "futures_outcome",
        "outcomes": null,
        "checked": false,
        "rule": "No usable price, and the market settled longer ago than the MEASURED Kalshi retention horizon \u2014 every probe at this age returned 404, so no upstream API still holds the price. This is permanently unrecoverable and must never be counted as work outstanding."
      },
      {
        "key": "unpriced_recoverable",
        "unit": "futures_outcome",
        "outcomes": null,
        "checked": false,
        "rule": "No usable price, but the market settled recently enough that the price is still expected to be retrievable, or the source is not subject to the retention horizon at all. This IS work outstanding."
      },
      {
        "key": "unpriced_unknown_age",
        "unit": "futures_outcome",
        "outcomes": null,
        "checked": false,
        "rule": "No usable price and no settlement date, so reachability cannot be established either way. Deliberately its own tier: folding it into either neighbour would invent a fact, which is the exact failure this census exists to prevent."
      }
    ],
    "resolved_futures_outcomes": null,
    "reconciles": false,
    "residual": null,
    "violations": [
      "REACHABILITY_UNAVAILABLE"
    ]
  },
  "observation_bridge": {
    "unit": "curve_observation",
    "futures_outcomes_plotted": 412889,
    "sportsbook_curve_legs": null,
    "published_curve_observations": 737431,
    "reconciles": false,
    "residual": null
  },
  "invariants": {
    "ok": false,
    "violations": [
      "OBSERVATION_BRIDGE_UNKNOWN"
    ],
    "published_outcomes_crosscheck": 412889
  }
} as const;
